// packages/platforms/vue2/src/core4vue/widgets/GraphOperateStuff.vue
<template>
  <div v-if="options && (options.creatingNodePlot || options.creatingSelection)" class="rel-operate">
    <div style="position: relative;">
      <SeeksRGNode v-if="options.creatingNodePlot && options.showTemplateNode" :node-props="options.newNodeTemplate">
        <template #node>
          <slot :node="options.newNodeTemplate" name="node-template" />
        </template>
      </SeeksRGNode>
      <div
          v-if="options.creatingSelection"
          class="rel-selection"
          :style="{
            left: options.selectionView.x + 'px',
            top: options.selectionView.y + 'px',
            width: options.selectionView.width + 'px',
            height: options.selectionView.height + 'px',
          }"
      >

      </div>
    </div>
  </div>
</template>

<script lang="ts">
import SeeksRGNode from "../RGNode.vue";

export default {
  name: 'GraphOperateStuff',
  components: {SeeksRGNode},
  inject: ['graph', 'graphInstance'],
  computed: {
    relationGraph() {
      return this.graphInstance();
    },
    options() {
      return this.graph.options;
    }
  },
  mounted() {
  },
  methods: {

  }
};
</script>

<style scoped>
</style>

// packages/platforms/react/src/relation-graph/src/core4react/widgets/GraphOperateStuff.tsx
import React, {useContext} from 'react';
import SeeksRGNode from '../RGNode';
import {RelationGraphStoreContext} from '../store/reducers/StockStore';
import type { RGNodeSlotProps } from '../../../../../../../relation-graph-models/types';

export interface GraphOperateStuffProps {
  nodeSlot?: React.FC<RGNodeSlotProps>
}
const GraphOperateStuff: React.FC<GraphOperateStuffProps> = ({nodeSlot}) => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const options = relationGraph && relationGraph.options;
  return (
    (options && (options.creatingNodePlot || options.creatingSelection)) ?
      <div className="rel-operate">
        <div style={{position: 'relative'}}>
          {options.creatingNodePlot && options.showTemplateNode &&
                  <SeeksRGNode
                    nodeProps={options.newNodeTemplate}
                    NodeSlot={nodeSlot}
                  />
          }
          {
            options.creatingSelection &&
              <div
                className="rel-selection"
                style={{
                  left: options.selectionView.x + 'px',
                  top: options.selectionView.y + 'px',
                  width: options.selectionView.width + 'px',
                  height: options.selectionView.height + 'px',
                }}
              >
              </div>
          }
        </div>
      </div>
      :
      <div></div>
  );
};

export default GraphOperateStuff;
