// packages/platforms/vue2/src/core4vue/widgets/GraphLoading.vue
<template>
  <div
      class="rel-graph-loading"
      :class="{'rel-graph-loading-hide': !options.graphLoading}"
      @click="clickGraphMask"
  >
    <div v-if="options.graphLoadingText" class="rel-graph-loading-message">
      <svg class="c-graph-loading-icon" aria-hidden="true"><use xlink:href="#icon-lianjiezhong"></use></svg>
      {{options.graphLoadingText || 'Loading...'}}
    </div>
  </div>
</template>

<script lang="ts">

export default {
  name: 'GraphLoading',
  data() {
    return {
    };
  },
  inject: ['graph', 'graphInstance'],
  computed: {
    relationGraph() {
      return this.graphInstance();
    },
    options() {
      return this.graph.options;
    }
  },
  methods: {
    clickGraphMask(e) {
      this.relationGraph.clickGraphMask(e);
    }
  }
};
</script>

// packages/platforms/react/src/relation-graph/src/core4react/widgets/GraphLoading.tsx
import React, { useContext, useState } from 'react';
import { RelationGraphStoreContext } from '../store/reducers/StockStore';

const GraphLoading: React.FC = () => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const options = relationGraph && relationGraph.options;
  const clickGraphMask = (e) => {
    relationGraph.clickGraphMask(e);
  }
  return (
    <>
    {
      options && <div
    className={`rel-graph-loading ${!options.graphLoading ? 'rel-graph-loading-hide' : ''}`}
    onClick={(e) => {clickGraphMask(e);}}
  >
    <div className="rel-graph-loading-message">
      <svg className="c-graph-loading-icon" aria-hidden="true">
        <use xlinkHref="#icon-lianjiezhong"></use>
      </svg>
      Loading...
    </div>
  </div>
}
    </>
  );
};

export default GraphLoading;
