// packages/platforms/vue2/src/core4vue/widgets/GraphWatermark.vue
<template>
  <div
      v-show="show"
      class="rel-watermark"
      :class="['rel-watermark-' + position]"
      ref="watermarkRef"
  >
    <slot />
  </div>
</template>

<script lang="ts">

export default {
  name: 'GraphWatermark',
  components: {},
  props: {
    forImage: {
      mustUseProp: false,
      default: true,
      type: Boolean
    },
    forDisplay: {
      mustUseProp: false,
      default: true,
      type: Boolean
    },
    position: {
      mustUseProp: false,
      default: 'br',
      type: String
    },
    width: {
      mustUseProp: false,
      default: '200px',
      type: String
    },
    height: {
      mustUseProp: false,
      default: '200px',
      type: String
    }
  },
  inject: ['graph', 'graphInstance'],
  computed: {
    relationGraph() {
      return this.graphInstance();
    },
    options() {
      return this.graph.options;
    },
    show() {
      let show = false;
      if (this.options.snapshotting) {
        if (this.forImage === false) {
          show = false;
        } else {
          show = true;
        }
      } else {
        if (this.forDisplay === true) {
          show = true;
        } else {
          show = false;
        }
      }
      return show;
    }
  },
  mounted() {
    this.$refs.watermarkRef.style.setProperty('--mv-width', this.width);
    this.$refs.watermarkRef.style.setProperty('--mv-height', this.height);
    this.relationGraph.setWatermarkDom(this.$refs.watermarkRef, this.forImage, this.forDisplay, this.position);
  },
  methods: {

  },
  beforeDestroy() {
    this.relationGraph.setWatermarkDom(null, this.forImage, this.forDisplay);
  }
};
</script>

<style scoped>
</style>

// packages/platforms/react/src/relation-graph/src/core4react/widgets/GraphWatermark.tsx
import React, {useRef, useEffect, useContext} from 'react';
import {RGWatermarkProps} from "../../../../types";
import {RelationGraphStoreContext, RGUpdateSingalContext} from "../store/reducers/StockStore";

const GraphWatermark: React.FC<RGWatermarkProps> = ({ children, forDisplay, forImage, position, width, height }) => {
  const graphInstance = useContext(RelationGraphStoreContext);
  const updateSingal = useContext(RGUpdateSingalContext);
  const options = graphInstance && graphInstance.options;
  const $watermarkRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    $watermarkRef.current!.style.setProperty('--mv-width', width || '200px');
    $watermarkRef.current!.style.setProperty('--mv-height', height || '200px');
    // Replace the following line with the appropriate logic for setting the watermark in your React app
    graphInstance.setWatermarkDom($watermarkRef.current!, forImage, forDisplay, position);
    return () => {
      graphInstance.setWatermarkDom(null, forDisplay, forImage);
    };
  }, [width, height]);
  let show = false;
  if (options.snapshotting) {
    if (forImage === false) {
      show = false;
    } else {
      show = true;
    }
  } else {
    if (forDisplay === true) {
      show = true;
    } else {
      show = false;
    }
  }
  return (
    <div
      className={`rel-watermark rel-watermark-${position || 'br'}`}
      style={{ display: show ? 'block' : 'none' }}
      ref={$watermarkRef}
    >
      {children}
    </div>
  );
};

export default GraphWatermark;
