// packages/platforms/vue3/src/relation-graph/src/core4vue3/widgets/GraphWatermark.vue
<template>
  <div
      v-show="show"
      class="rel-watermark"
      :class="['rel-watermark-' + (position || 'br')]"
      ref="$watermarkRef"
  >
    <slot />
  </div>
</template>

<script lang="ts" setup>
import {computed, inject, onMounted, onUnmounted, ref} from "vue";
import {RGWidgetPosition} from "../../../../types";
import {graphKey} from "../../../../constants";

const props = withDefaults(defineProps<{
  forImage?: boolean,
  forDisplay?: boolean,
  position?: RGWidgetPosition,
  width?: string,
  height?: string,
}>(), {
  forImage: true,
  forDisplay: false,
  position: 'br',
  width: '200px',
  height: '200px',
}); // RGWatermarkProps
const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})
const graphInstance = computed(() => {
  return graph!.instance!;
})
const show = computed(() => {
  let isShow = false;
  if (options.value.snapshotting) {
    if (props.forImage === false) {
      isShow = false;
    } else {
      isShow = true;
    }
  } else {
    if (props.forDisplay === true) {
      isShow = true;
    } else {
      isShow = false;
    }
  };
  return isShow;
});
const $watermarkRef = ref();
onMounted(() => {
  $watermarkRef.value.style.setProperty('--mv-width', props.width || '200px');
  $watermarkRef.value.style.setProperty('--mv-height', props.height || '200px');
  graphInstance.value.setWatermarkDom($watermarkRef.value, props.forImage, props.forDisplay, props.position);
});
onUnmounted(() => {
  graphInstance.value.setWatermarkDom(null, props.forImage, props.forDisplay);
});
</script>

// packages/platforms/react/src/relation-graph/src/core4react/widgets/GraphWatermark.tsx
import React, {useRef, useEffect, useContext} from 'react';
import {RGWatermarkProps} from "../../../../types";
import {RelationGraphStoreContext, RGUpdateSingalContext} from "../store/reducers/StockStore";

const GraphWatermark: React.FC<RGWatermarkProps> = ({ children, forDisplay, forImage, position, width, height }) => {
  const graphInstance = useContext(RelationGraphStoreContext);
  const updateSingal = useContext(RGUpdateSingalContext);
  const options = graphInstance && graphInstance.options;
  const $watermarkRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    $watermarkRef.current!.style.setProperty('--mv-width', width || '200px');
    $watermarkRef.current!.style.setProperty('--mv-height', height || '200px');
    // Replace the following line with the appropriate logic for setting the watermark in your React app
    graphInstance.setWatermarkDom($watermarkRef.current!, forImage, forDisplay, position);
    return () => {
      graphInstance.setWatermarkDom(null, forDisplay, forImage);
    };
  }, [width, height]);
  let show = false;
  if (options.snapshotting) {
    if (forImage === false) {
      show = false;
    } else {
      show = true;
    }
  } else {
    if (forDisplay === true) {
      show = true;
    } else {
      show = false;
    }
  }
  return (
    <div
      className={`rel-watermark rel-watermark-${position || 'br'}`}
      style={{ display: show ? 'block' : 'none' }}
      ref={$watermarkRef}
    >
      {children}
    </div>
  );
};

export default GraphWatermark;
