// packages/platforms/react/src/relation-graph/src/core4react/editing/RGEditingLineController.tsx
import React, {useContext, useEffect, useState} from 'react';
import {RGLineEditPoint} from '../../../../types';
import {RelationGraphStoreContext, RGUpdateSingalContext} from '../store/reducers/StockStore';

const RGEditingLineController:React.FC<{textEditable?: boolean}> = ({ textEditable, children }) => {
  const updateSingal = useContext(RGUpdateSingalContext);
  const graphInstance = useContext(RelationGraphStoreContext);
  const options = graphInstance && graphInstance.options;
  const show = options.editingLineController.show;
  const text = options.editingLineController.line && options.editingLineController.line.text;
  const [editing, setEditing] = useState(false);
  const [lineText, setLineText] = useState('');
  useEffect(() => {
    if (!show) {
      setEditing(false);
      setLineText('');
    }
  }, [show]);
  useEffect(() => {
    setLineText(text || '');
  }, [text]);
  useEffect(() => {
    graphInstance.updateEditingLineView();
  }, [lineText]);
  const onMouseDown = (type: RGLineEditPoint, event: React.MouseEvent) => {
    graphInstance.startMoveLineVertex(type, event.nativeEvent);
  };

  const startMoveText = ($event: React.MouseEvent) => {
    graphInstance.startMoveLineText($event.nativeEvent);
  };

  if (!options.editingLineController.show) {
    return null;
  }
  const startEditingLineText = (_event: React.MouseEvent) => {
    setEditing(!editing);
  };
  const onLineTextChange = (_event: React.FocusEvent) => {
    const line = options.editingLineController.line;
    if (line) {
      line.text = lineText;
    }
  };

  return (
    <div className="rel-editing-line-ctrl">
      {children}
      <div
        className="rel-line-ctrl-dot start-dot"
        style={{
          left: options.editingLineController.startPoint.x + 'px',
          top: options.editingLineController.startPoint.y + 'px',
        }}
        onMouseDown={(event) => onMouseDown('start', event)}
      ></div>
      <div
        className="rel-line-ctrl-dot end-dot"
        style={{
          left: options.editingLineController.endPoint.x + 'px',
          top: options.editingLineController.endPoint.y + 'px',
        }}
        onMouseDown={(event) => onMouseDown('end', event)}
      ></div>
      {textEditable && options.editingLineController.line && <div
        className={['rel-line-ctrl-text', (editing && 'rel-line-ctrl-text-editing')].join(' ')}
        style={{
          width: options.editingLineController.text.width + 'px',
          height: options.editingLineController.text.height + 'px',
          left: options.editingLineController.text.x + 'px',
          top: options.editingLineController.text.y + 'px'
        }}
        onDoubleClick={(event) => startEditingLineText(event)}
        onMouseDown={(event) => startMoveText(event)}
      >
        {
          !editing ? <span>{text}</span>
            :<input className="rel-line-text-input"
              value={lineText}
              onChange={(event) => {setLineText(event.target.value);}}
              onBlur={(event) => onLineTextChange(event)} />
        }
      </div>
      }
    </div>
  );
};

export default RGEditingLineController;

// packages/platforms/vue2/src/core4vue/editing/RGEditingLineController.vue
<template>
  <div
    v-if="show"
    class="rel-editing-line-ctrl"
  >
    <slot />
    <div class="rel-line-ctrl-dot start-dot"
         :style="{
            left: options.editingLineController.startPoint.x + 'px',
            top: options.editingLineController.startPoint.y + 'px'
          }"
         @mousedown="onMouseDown('start', $event)"
    ></div>
    <div class="rel-line-ctrl-dot end-dot"
         :style="{
            left: options.editingLineController.endPoint.x + 'px',
            top: options.editingLineController.endPoint.y + 'px'
          }"
         @mousedown="onMouseDown('end', $event)"
    ></div>
    <div v-if="textEditable && options.editingLineController.line"
         :class="['rel-line-ctrl-text', (editing && 'rel-line-ctrl-text-editing')]"
         :style="{
            width: options.editingLineController.text.width + 'px',
            height: options.editingLineController.text.height + 'px',
            left: options.editingLineController.text.x + 'px',
            top: options.editingLineController.text.y + 'px'
          }"
         @dblclick="startEditingLineText"
         @mousedown="startMoveText($event)"
    >
      <span v-if="!editing">{{text}}</span>
      <input v-else class="rel-line-text-input" v-model="lineText" @blur="onLineTextChange" />
    </div>
  </div>
</template>

<script lang="ts">

export default {
  name: 'RGEditingLineController',
  components: {},
  inject: ['graph', 'graphInstance'],
  props: {
    textEditable: {
      mustUseProp: false,
      default: false
    }
  },
  computed: {
    options() {
      return this.graph.options;
    },
    relationGraph() {
      return this.graphInstance();
    },
    show() {
      return this.options.editingLineController.show;
    },
    text() {
      return this.options.editingLineController.line && this.options.editingLineController.line.text;
    }
  },
  data() {
    return {
      lineText: '',
      editing: false
    };
  },
  watch: {
    show(newValue:string) {
      if (!newValue) {
        this.editing = false;
        this.lineText = '';
      }
    },
    text(newValue:string) {
      if (newValue) {
        this.lineText = newValue;
        this.$nextTick(() => {
          this.relationGraph.updateEditingLineView();
        });
      }
    }
  },
  methods: {
    onMouseDown(type, $event) {
      this.relationGraph.startMoveLineVertex(type, $event);
    },
    startMoveText($event) {
      this.relationGraph.startMoveLineText($event);
    },
    startEditingLineText($event) {
      this.editing = !this.editing;
    },
    onLineTextChange($event) {
      const line = this.options.editingLineController.line;
      if (line) {
        line.text = $event.target.value;
      }
    }
  }
};
</script>

<style scoped>
</style>
