// packages/platforms/react/src/relation-graph/src/core4react/editing/RGEditingCreateLineHandle.tsx
import React, { useContext } from 'react';
import {RGWidgetPosition, RGCreateLineHandleProps} from '../../../../types';
import {RelationGraphStoreContext, RGUpdateSingalContext} from '../store/reducers/StockStore';

const RGEditingCreateLineHandle:React.FC<RGCreateLineHandleProps> = ({ lineTemplate, children }) => {
  const updateSingal = useContext(RGUpdateSingalContext);
  const graphInstance = useContext(RelationGraphStoreContext);
  const options = graphInstance && graphInstance.options;

  const onMouseDown = (type: RGWidgetPosition, event: React.MouseEvent) => {
    graphInstance.startCreateLineByTemplate(type, lineTemplate, event.nativeEvent);
  };

  if (options.editingController.nodes.length !== 1) {
    return null;
  }

  return (
    <div
      className="rel-editing-line-handle"
      onMouseDown={(event) => onMouseDown('br', event)}
    >
      {children}
    </div>
  );
};

export default RGEditingCreateLineHandle;

// packages/platforms/vue2/src/core4vue/editing/RGEditingCreateLineHandle.vue
<template>
  <div
    v-if="options.editingController.nodes.length === 1"
    class="rel-editing-line-handle"
    @mousedown="onMouseDown('br', $event)"
  >
    <slot />
  </div>
</template>

<script lang="ts">

export default {
  name: 'RGEditingCreateLineHandle',
  components: {},
  inject: ['graph', 'graphInstance'],
  props: {
    lineTemplate: {
      mustUseProp: false,
      default: () => { return {}; },
      type: Object
    }
  },
  computed: {
    options() {
      return this.graph.options;
    },
    relationGraph() {
      return this.graphInstance();
    }
  },
  data() {
    return {
    };
  },
  methods: {
    onMouseDown(type, $event) {
      this.relationGraph.startCreateLineByTemplate(type, this.lineTemplate, $event);
    }
  }
};
</script>

<style scoped>
</style>
