// packages/platforms/react/src/relation-graph/src/core4react/editing/RGMiniView.tsx
import React, { useEffect, useRef } from 'react';
import { useContext } from 'react';
import {RelationGraphStoreContext, RGUpdateSingalContext} from '../store/reducers/StockStore';
import {RGMiniViewProps} from "../../../../../../../relation-graph-models/types";

const RGMiniView:React.FC<RGMiniViewProps> = ({ position = 'br', width, height }) => {
  const graphInstance = useContext(RelationGraphStoreContext);
  const updateSingal = useContext(RGUpdateSingalContext);
  const options = graphInstance && graphInstance.options;
  const $rgMiniView = useRef<HTMLDivElement>(null);
  const $rgMiniViewCanvas = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    options.showMiniView = true;
    $rgMiniView.current!.style.setProperty('--mv-width', width || '150px');
    $rgMiniView.current!.style.setProperty('--mv-height', height || '150px');
    graphInstance.setMiniViewCanvas($rgMiniViewCanvas.current!);

    return () => {
      options.showMiniView = false;
    };
  }, []);

  const onMouseDown = (e: React.MouseEvent) => {
    graphInstance.onVisiableViewHandleDragStart(e.nativeEvent);
  };

  const onClickCanvas = async(e: React.MouseEvent) => {
    graphInstance.resetByVisiableView(e.nativeEvent);
  };

  return (
    <div
      className={`rel-miniview rel-miniview-${position}`}
      ref={$rgMiniView}
    >
      <canvas
        ref={$rgMiniViewCanvas}
        className={
          options.miniViewVisibleHandle.emptyContent
            ? 'rel-mv-canvas-reset'
            : ''
        }
        onClick={onClickCanvas}
      />
      <div
        className="rel-mv-visible-area"
        onMouseDown={onMouseDown}
        style={{
          left: options.miniViewVisibleHandle.x + 'px',
          top: options.miniViewVisibleHandle.y + 'px',
          width: options.miniViewVisibleHandle.width + 'px',
          height: options.miniViewVisibleHandle.height + 'px',
        }}
      ></div>
    </div>
  );
};

export default RGMiniView;

// packages/platforms/vue2/src/core4vue/editing/RGMiniView.vue
<template>
  <div
    class="rel-miniview"
    :class="['rel-miniview-' + position]"
    ref="rgMiniView"
  >
    <canvas
      ref="rgMiniViewCanvas"
      :class="{
      'rel-mv-canvas-reset': options.miniViewVisibleHandle.emptyContent
      }"
      @click="onClickCanvas"
    />
    <div
      class="rel-mv-visible-area"
      @mousedown="onMouseDown"
      :style="{
      left: options.miniViewVisibleHandle.x + 'px',
      top: options.miniViewVisibleHandle.y + 'px',
      width: options.miniViewVisibleHandle.width + 'px',
      height: options.miniViewVisibleHandle.height + 'px'
    }"
    ></div>
  </div>
</template>

<script lang="ts">
import {RGUserEvent} from "../../../../../relation-graph-models/types";

export default {
  name: 'RGMiniView',
  components: {},
  props: {
    position: {
      mustUseProp: false,
      default: 'br',
      type: String
    },
    width: {
      mustUseProp: false,
      default: '200px',
      type: String
    },
    height: {
      mustUseProp: false,
      default: '200px',
      type: String
    }
  },
  inject: ['graph', 'graphInstance'],
  computed: {
    options() {
      return this.graph.options;
    },
    relationGraph() {
      return this.graphInstance();
    }
  },
  data() {
    return {
    };
  },
  mounted() {
    this.options.showMiniView = true;
    this.$refs.rgMiniView.style.setProperty('--mv-width', this.width);
    this.$refs.rgMiniView.style.setProperty('--mv-height', this.height);
    this.relationGraph.setMiniViewCanvas(this.$refs.rgMiniViewCanvas);
  },
  methods: {
    onMouseDown(e: RGUserEvent) {
      this.relationGraph.onVisiableViewHandleDragStart(e);
    },
    onClickCanvas(e: RGUserEvent) {
      this.relationGraph.resetByVisiableView(e);
    }
  },
  beforeDestroy() {
    this.options.showMiniView = false;
  }
};
</script>

<style scoped>
</style>
