// packages/platforms/react/src/relation-graph/src/core4react/widgets/GraphDebugPanel.tsx
import React, { useContext, useState } from 'react';
import { devLog } from '../../../../../../../relation-graph-models/utils/RGCommon';
import { RGUpdateContext, RelationGraphStoreContext } from '../store/reducers/StockStore';

const GraphDebugPanel: React.FC = () => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const updateView = useContext(RGUpdateContext);
  const options = relationGraph.options;
  const [showSettingPanel, setShowSettingPanel] = useState(false);
  const toggleSettingPanel = () => {
    setShowSettingPanel(!showSettingPanel);
  };
  const printOptions = () => {
    relationGraph.printOptions();
  };
  const printData = () => {
    relationGraph.getGraphJsonData();
  };
  const enableDevlog = () => {
    relationGraph.enableDebugLog(!options.debug);
    devLog('debugLog:', options.debug);
    updateView();
  };
  return (
    <div>
      <div className="c-setting-panel-button" onClick={()=>{toggleSettingPanel();}}>
        Debug
      </div>
      {
        showSettingPanel &&
        <div className="c-setting-panel">
          <div className="c-debug-tools-row">
            <button onClick={()=>{printOptions();}}>print options in console</button>
          </div>
          <div className="c-debug-tools-row">
            <button onClick={()=>{printData();}}>print json data in console</button>
          </div>
          <div className="c-debug-tools-row">
            debug log status: {options.debug ? 'true' : 'false'}
            <button onClick={()=>{enableDevlog();}}>
              { options.debug ? 'disable' : 'enable' } debug log
            </button>
          </div>
        </div>
      }
    </div>
  );
};

export default GraphDebugPanel;

// packages/platforms/vue2/src/core4vue/widgets/GraphDebugPanel.vue
<template>
  <div>
    <div :class="[]" class="c-setting-panel-button" @click="toggleSettingPanel">
      Debug
    </div>
    <div v-if="showSettingPanel" :class="[]" class="c-setting-panel">
      <div class="c-debug-tools-row"><button @click="printOptions">print options in console</button></div>
      <div class="c-debug-tools-row"><button @click="printData">print json data in console</button></div>
      <div class="c-debug-tools-row">debug log status: {{options.debug}}<button @click="enableDevlog">{{options.debug?'disable':'enable'}} debug log</button></div>
    </div>
  </div>
</template>

<script lang="ts">

import { devLog } from '../../../../../relation-graph-models/utils/RGCommon';

export default {
  name: 'GraphSettingPanel',
  data() {
    return {
      search_text: '',
      showSettingPanel: false,
      currentLayoutName: ''
    };
  },
  inject: ['graph', 'graphInstance'],
  computed: {
    relationGraph() {
      return this.graphInstance();
    },
    options() {
      return this.graph.options;
    }
  },
  methods: {
    toggleSettingPanel() {
      this.showSettingPanel = !this.showSettingPanel;
    },
    printOptions() {
      this.relationGraph.printOptions();
    },
    printData() {
      this.relationGraph.printData();
    },
    enableDevlog() {
      this.relationGraph.enableDebugLog(!this.options.debug);
      devLog('debugLog:', this.options.debug);
    }
  }
};
</script>
