// relation-graph-react/src/relation-graph/src/core4react/RGLinePath.tsx
import React, { useContext } from 'react';
import { RelationGraphStoreContext } from './store/reducers/StockStore';
import type { RGLineProps } from './RGLineSmart';

const RGLinePath: React.FC<RGLineProps> = ({link,relation,relationIndex}) => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const options = relationGraph.options;
  const checked = link.seeks_id === options.checkedLineId;

  const pathData = () => {
    const { path } = relationGraph.createLinePath(
      link,
      relation,
      relationIndex
    );
    return path;
  };
  const showStartArrow = relation.showStartArrow ? relationGraph.getArrow(relation, link, true) : undefined;
  const showEndArrow = relation.showEndArrow ? relationGraph.getArrow(relation, link, false) : undefined;
  return (
    <path
      id={`${options.instanceId}-${link.seeks_id}-${relationIndex}`}
      d={pathData()}
      stroke={relation.color ? relation.color : options.defaultLineColor}
      style={{
        opacity: relation.opacity,
        strokeWidth: `${
          relation.lineWidth ? relation.lineWidth : options.defaultLineWidth
        }px`,
      }}
      markerStart={showStartArrow}
      markerEnd={showEndArrow}
      className={`c-rg-line-path ${relation.styleClass} ${
        checked ? 'c-rg-line-checked' : ''
      }`}
      fill="none"
    />
  );
};

export default RGLinePath;

// relation-graph-vue2/src/core4vue/RGLinePath.vue
<template>
  <path
      :id="relationGraph.options.instanceId + '-' + link.seeks_id + '-' + relationIndex"
      :d="pathData"
      :stroke="checked ? relationGraph.options.checkedLineColor : (relation.color?relation.color:relationGraph.options.defaultLineColor)"
      :style="{'opacity': relation.opacity, 'stroke-width': (relation.lineWidth?relation.lineWidth:relationGraph.options.defaultLineWidth) + 'px'}"
      :marker-start="relation.showStartArrow && relationGraph.getArrow(relation, link, true)"
      :marker-end="relation.showEndArrow && relationGraph.getArrow(relation, link, false)"
      :class="[relation.styleClass, checked?'c-rg-line-checked':'']"
      fill="none" />
</template>
<script>
export default {
  name: 'SeeksRGLink',
  props: {
    relationGraph: {
      mustUseProp: true,
      default: () => { return {}; },
      type: Object
    },
    link: {
      mustUseProp: true,
      default: () => { return {}; },
      type: Object
    },
    relation: {
      mustUseProp: true,
      default: () => { return {}; },
      type: Object
    },
    relationIndex: {
      mustUseProp: true,
      default: () => { return 0; },
      type: Number
    }
  },
  computed: {
    checked() {
      return this.link.seeks_id === this.relationGraph.options.checkedLineId;
    },
    pathData() {
      const { path, textPosition } = this.relationGraph.createLinePath(
        this.link,
        this.relation,
        this.relationIndex
      );
      return path;
    }
  },
  data() {
    return {
      is_flashing: false
    };
  },
  show() {
    this.isShow = true;
  },
  methods: {
  }
};
</script>
