// relation-graph-react/src/relation-graph/src/core4react/widgets/GraphMiniToolBar.tsx
import React, { useContext } from 'react';
import { RGUpdateContext, RelationGraphStoreContext } from '../store/reducers/StockStore';

const GraphMiniToolBar: React.FC = () => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const updateView = useContext(RGUpdateContext);
  const refresh = async() => {
    await relationGraph.refresh();
    updateView();
  };
  const updateViewLoop = () => {
    if (relationGraph.options.autoLayouting) {
      updateView();
      requestAnimationFrame(() => { updateViewLoop(); });
    }
  };
  const toggleAutoLayout = () => {
    relationGraph.startAutoLayout();
    // updateViewLoop();
  };
  const toogleFullScreen = () => {
    relationGraph.fullscreen();
    updateView();
  };
  const downloadAsImage = () => {
    relationGraph.downloadAsImage('png');
  };
  const zoomToFit = async () => {
    const instance = relationGraph;
    await instance.setZoom(100);
    await instance.moveToCenter();
    await instance.zoomToFit();
    updateView();
  };
  const addZoom = (buff:number) => {
    relationGraph.zoom(buff);
    updateView();
  };
  const options = relationGraph && relationGraph.options;
  return (
    <div
      className={[
        'rel-toolbar',
        'rel-toolbar-h-' + options.toolBarPositionH,
        'rel-toolbar-v-' + options.toolBarPositionV,
        'rel-toolbar-' + options.toolBarDirection
      ].join(' ')}
    >
      {options.allowShowFullscreenMenu &&
          <div title="全屏/退出全屏" className="c-mb-button" onClick={()=>{toogleFullScreen();}}>
            <svg className="rg-icon" aria-hidden="true"><use xlinkHref="#icon-resize-"></use></svg>
          </div>}
      {options.allowShowZoomMenu &&
          <React.Fragment>
            <div title="放大" className="c-mb-button" onClick={() => {addZoom(20);}}>
              <svg className="rg-icon" aria-hidden="true"><use xlinkHref="#icon-fangda"></use></svg>
            </div>
            <div className="c-current-zoom" onDoubleClick={() => {zoomToFit();}}>{options.canvasZoom}%</div>
            <div title="缩小" className="c-mb-button" onClick={()=>{addZoom(-20);}}>
              <svg className="rg-icon" aria-hidden="true"><use xlinkHref="#icon-suoxiao"></use></svg>
            </div>
          </React.Fragment>
      }

      {options.allowAutoLayoutIfSupport && options.isNeedShowAutoLayoutButton &&
          <div
            title="options.autoLayouting?'点击停止自动布局':'点击开始自动调整布局'"
            className={[
              'c-mb-button',
              options.autoLayouting && 'c-mb-button-on'
            ].join(' ')}
            onClick={()=>{toggleAutoLayout();}}
          >
            {
              !options.autoLayouting ?
                <svg className="rg-icon" aria-hidden="true">
                  <use xlinkHref="#icon-zidong"></use>
                </svg>
                :
                <svg className="c-loading-icon rg-icon" aria-hidden="true">
                  <use xlinkHref="#icon-lianjiezhong"></use>
                </svg>
            }
          </div>
      }
      {options.allowShowRefreshButton &&
          <div title="刷新" className="c-mb-button" onClick={()=>{refresh();}}>
            <svg className="rg-icon" aria-hidden="true"><use xlinkHref="#icon-ico_reset"></use></svg>
          </div>
      }
      {options.allowShowDownloadButton &&
          <div title="下载图片" className="c-mb-button" onClick={()=>{downloadAsImage();}}>
            <svg className="rg-icon" aria-hidden="true"><use xlinkHref="#icon-tupian"></use></svg>
          </div>
      }
      <div style={{clear: 'both'}}></div>
    </div>
  );
};

export default GraphMiniToolBar;

// relation-graph-vue3/src/relation-graph/src/core4vue3/widgets/GraphMiniToolBar.vue
<script lang="ts" setup>
import {computed, inject, onMounted, ref} from 'vue'
import {graphInstanceKey, graphKey} from '../../../../constants'
const graphInstance$ = inject(graphInstanceKey)
const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})
onMounted(() => {
})
const refresh = () => {
  graphInstance$?.value!.refresh()
}
const toggleAutoLayout = () => {
  graphInstance$?.value!.startAutoLayout()
}
const downloadAsImage = () => {
  graphInstance$?.value!.downloadAsImage('png')
}
const zoomToFit = async () => {
  const instance = graphInstance$?.value!;
  await instance.setZoom(100);
  await instance.moveToCenter();
  await instance.zoomToFit();
}
const addZoom = (buff:number) => {
  graphInstance$?.value!.zoom(buff)
}
const doFullscreen = () => {
  graphInstance$?.value!.fullscreen()
}
</script>
<template>
  <div
      class="rel-toolbar"
      :class="['rel-toolbar-h-' + options.toolBarPositionH, 'rel-toolbar-v-' + options.toolBarPositionV, 'rel-toolbar-' + options.toolBarDirection]"
  >
    <div v-if="options.allowShowFullscreenMenu" title="全屏/退出全屏" class="c-mb-button" style="margin-top: 0px;" @click="doFullscreen()">
      <svg class="rg-icon" aria-hidden="true"><use xlink:href="#icon-resize-"></use></svg>
    </div>
    <div v-if="options.allowShowZoomMenu" title="放大" class="c-mb-button" @click="addZoom(20)">
      <svg class="rg-icon" aria-hidden="true"><use xlink:href="#icon-fangda"></use></svg>
    </div>
    <div v-if="options.allowShowZoomMenu" class="c-current-zoom" @dblclick="zoomToFit">{{ options.canvasZoom }}%</div>
    <div v-if="options.allowShowZoomMenu" title="缩小" class="c-mb-button" style="margin-top:0px;" @click="addZoom(-20)">
      <svg class="rg-icon" aria-hidden="true"><use xlink:href="#icon-suoxiao"></use></svg>
    </div>
    <div v-if="options.allowAutoLayoutIfSupport && options.isNeedShowAutoLayoutButton" :title="options.autoLayouting?'点击停止自动布局':'点击开始自动调整布局'" :class="{'c-mb-button-on':options.autoLayouting}" class="c-mb-button" @click="toggleAutoLayout">
      <svg v-if="!options.autoLayouting" class="rg-icon" aria-hidden="true"><use xlink:href="#icon-zidong"></use></svg>
      <svg v-else class="c-loading-icon rg-icon" aria-hidden="true"><use xlink:href="#icon-lianjiezhong"></use></svg>
    </div>
    <div v-if="options.allowShowRefreshButton" title="刷新" class="c-mb-button" @click="refresh">
      <svg class="rg-icon" aria-hidden="true"><use xlink:href="#icon-ico_reset"></use></svg>
    </div>
    <div v-if="options.allowShowDownloadButton" title="下载图片" class="c-mb-button" @click="downloadAsImage">
      <svg class="rg-icon" aria-hidden="true"><use xlink:href="#icon-tupian"></use></svg>
    </div>
    <div style="clear: both;"></div>
  </div>
</template>
