// packages/platforms/react/src/relation-graph/src/core4react/RGCanvas.tsx
import React, { useContext, useEffect, useRef } from 'react';
import { devLog } from '../../../../../../relation-graph-models/utils/RGCommon';
import { RelationGraphStoreContext } from './store/reducers/StockStore';
import type {
  RGLineSlotProps,
  RGNodeSlotProps,
  RelationGraphInstance
} from '../../../../../../relation-graph-models/types';
import type { MutableRefObject} from 'react';
import RGSingleGraph from './RGGraph';
import {RGNodeExpandHolderProps} from "../../../types-react";
import RGEasyView from "./RGEasyView";

export interface RGCanvasProps {
  nodeSlot?: React.FC<RGNodeSlotProps> | React.ReactNode
  lineSlot?: React.FC<RGLineSlotProps> | React.ReactNode
  svgDefs?: React.FC | React.ReactNode
  canvasPlugSlot?: React.FC<{relationGraph: RelationGraphInstance}> | React.ReactNode
  canvasPlugAboveSlot?: React.ReactNode | React.ReactNode
  expandHolderSlot?: React.FC<RGNodeExpandHolderProps> | React.ReactNode
}
const RGCanvas: React.FC<RGCanvasProps> = (canvasProps) => {
  const relationGraph = useContext(RelationGraphStoreContext);
  // const updateView = useContext(RGUpdateContext);
  const seeksRGCanvas$ = useRef() as MutableRefObject<HTMLDivElement>;
  const rgMap$ = useRef() as MutableRefObject<HTMLDivElement>;
  // console.log('================== RGCanvas:', relationGraph.graphData.nodes.map(n=>n.text).join(','))
  const createCurrrentStyles = () => {
    return {
      width: `${relationGraph.options.canvasSize.width}px`,
      height: `${relationGraph.options.canvasSize.height}px`,
      marginLeft: `${relationGraph.options.canvasOffset.x}px`,
      marginTop: `${relationGraph.options.canvasOffset.y}px`,
      backgroundColor: 'transparent',
      transform: `scale(${relationGraph.options.canvasZoom! / 100},${
        relationGraph.options.canvasZoom! / 100
      })`,
      // 'transform-origin': (this.options.canvasOffset.zoom_buff_x * 100).toFixed(2) + '% ' + (this.options.canvasOffset.zoom_buff_y * 100).toFixed(2) + '%'
    };
  };
  const canvasSizeAndPosition = createCurrrentStyles();

  useEffect(() => {
    // console.log('[debug][RelationGraph-canvas] ready!');
    devLog('[RGCanvas mounted]');
    relationGraph.setCanvasDom(seeksRGCanvas$.current!);
    rgMap$.current && rgMap$.current.addEventListener('wheel', mouseListener);
    return () => {
      rgMap$.current && rgMap$.current.removeEventListener('wheel', mouseListener);
    };
  }, []);

  const mouseListener = (e:WheelEvent) => {
    relationGraph.onMouseWheel(e);
  };
  const onDragStart = (e:  React.MouseEvent|React.TouchEvent) => {
    if (e.type === "mousedown" && e.button !== 0) {
      return;
    }
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    relationGraph.onCanvasDragStart(e);
  };
  const contextmenu = (e:  React.MouseEvent|React.TouchEvent) => {
    e.preventDefault();
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    relationGraph.onContextmenu(e);
  };
  return (
    <div
      style={{
        width: '100%',
        height: '100%',
        backgroundImage: relationGraph.options.backgroundImage && `url(${relationGraph.options.backgroundImage})`,
        backgroundColor: relationGraph.options.backgroundColor,
      }}
      ref={rgMap$}
      className={[
        'rel-map',
        (relationGraph.options.canvasOpacity === 1 ? 'rel-map-ready':undefined),
        relationGraph.options.layoutClassName,
        relationGraph.options.backgroundImageNoRepeat
          ? 'rel-map-background-norepeat'
          : '',
      ].join(' ')}
      onContextMenu={($event) => {contextmenu($event);}}
      onMouseDown={($event)=>{onDragStart($event);}}
      onTouchStart={($event)=>{onDragStart($event);}}
    >
      <RGEasyView />
      <div
        ref={seeksRGCanvas$}
        style={canvasSizeAndPosition}
        className="rel-map-canvas"
      >
        <div className="rel-canvas-slot rel-canvas-slot-behind">
          {canvasProps.canvasPlugSlot && (typeof canvasProps.canvasPlugSlot === 'function' ? <canvasProps.canvasPlugSlot relationGraph={relationGraph} /> : canvasProps.canvasPlugSlot)}
        </div>
        <RGSingleGraph svgDefs={canvasProps.svgDefs} nodeSlot={canvasProps.nodeSlot} lineSlot={canvasProps.lineSlot} expandHolderSlot={canvasProps.expandHolderSlot} />
        <div className="rel-canvas-slot rel-canvas-slot-above">
          {canvasProps.canvasPlugAboveSlot}
        </div>
      </div>
    </div>
  );
};

export default RGCanvas;

// packages/platforms/vue2/src/core4vue/RGCanvas.vue
<template>
  <div
      :style="{width: '100%',height : '100%', 'background-color': (options.backgroundColor || undefined), 'background-image': (options.backgroundImage ? ('url('+options.backgroundImage+')') : undefined)}"
      class="rel-map"
      :class="[(options.canvasOpacity === 1 && 'rel-map-ready'), options.layoutClassName, (options.backgroundImageNoRepeat?'rel-map-background-norepeat':undefined)]"
      @contextmenu.prevent="contextmenu($event)"
      @mousedown.left="onDragStart($event)"
      @touchstart="onDragStart($event)"
      @wheel="mouseListener">
      <RGEasyView />
    <div ref="seeksRGCanvas" :style="canvasSizeAndPosition" class="rel-map-canvas">
      <div class="rel-canvas-slot rel-canvas-slot-behind">
        <slot name="canvas-plug" />
      </div>
      <RelationGraphSingleGraph>
        <template #node="{node}" >
          <slot :node="node" name="node" />
        </template>
        <template #line="{line, link}" >
          <slot :line="line" :link="link" name="line" />
        </template>
        <template #node-expand-holder="{nodeProps, expandHolderPosition, expandButtonClass, color, expandOrCollapseNode}">
          <slot
              name="node-expand-holder"
              :nodeProps="nodeProps"
              :expandHolderPosition="expandHolderPosition"
              :expandButtonClass="expandButtonClass"
              :color="color"
              :expandOrCollapseNode="expandOrCollapseNode"
          />
        </template>
      </RelationGraphSingleGraph>
      <div class="rel-canvas-slot rel-canvas-slot-above">
        <slot name="canvas-plug-above" />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import SeeksRGNode from './RGNode.vue';
import SeeksRGLink from './RGLink.vue';
import SeeksRGLinePath from './RGLinePath.vue';
import { devLog } from '../../../../relation-graph-models/utils/RGCommon';
import RelationGraphSingleGraph from "./RGGraph.vue";
import RGEasyView from "./RGEasyView.vue";

export default {
  name: 'RelationGraphCanvas',
  components: {RGEasyView, RelationGraphSingleGraph, SeeksRGNode, SeeksRGLink, SeeksRGLinePath },
  data() {
    return {

    };
  },
  inject: ['graph', 'graphInstance'],
  computed: {
    options() {
      return this.graph.options;
    },
    relationGraph() {
      return this.graphInstance();
    },
    canvasSizeAndPosition() {
      return {
        'width': `${this.options.canvasSize.width  }px`,
        'height': `${this.options.canvasSize.height  }px`,
        'margin-left': `${this.options.canvasOffset.x  }px`,
        'margin-top': `${this.options.canvasOffset.y  }px`,
        'background-color': 'transparent',
        'transform': `scale(${  this.options.canvasZoom / 100  },${  this.options.canvasZoom / 100  })`
        // 'transform-origin': (this.options.canvasOffset.zoom_buff_x * 100).toFixed(2) + '% ' + (this.options.canvasOffset.zoom_buff_y * 100).toFixed(2) + '%'
      };
    }
  },
  watch: {
  },
  created() {
    devLog('[RGCanvas created]');
  },
  mounted() {
    devLog('[RGCanvas mounted]');
    this.relationGraph.setCanvasDom(this.$refs.seeksRGCanvas);
  },
  beforeDestroy() {
  },
  methods: {
    mouseListener(e) {
      this.relationGraph.onMouseWheel(e);
    },
    onDragStart(e) {
      this.relationGraph.onCanvasDragStart(e);
    },
    contextmenu(e) {
      this.relationGraph.onContextmenu(e);
    }
  }
};
</script>
