// packages/platforms/react/src/relation-graph/src/core4react/RGEasyView.tsx
import React, {MutableRefObject, useContext, useEffect, useRef} from 'react';
import {RelationGraphStoreContext} from './store/reducers/StockStore';
import {RGCanvasProps} from './RGCanvas';
import { devLog } from '../../../../../../relation-graph-models/utils/RGCommon';

const RGCanvas: React.FC<RGCanvasProps> = (canvasProps) => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const options = relationGraph.options;
  const rgEasyCanvas$ = useRef() as MutableRefObject<HTMLCanvasElement>;

  useEffect(() => {
    devLog('[RGEasyView mounted]');
    relationGraph.setEasyViewCanvas(rgEasyCanvas$.current!);
  }, []);

  return (
    <div className={`rel-easy-view ${options.showEasyView ? 'rel-easy-view-active' : ''}`}>
      <canvas ref={rgEasyCanvas$} />
    </div>
  );
};

export default RGCanvas;

// packages/platforms/vue2/src/core4vue/RGEasyView.vue
<template>
    <div class="rel-easy-view" :class="{'rel-easy-view-active':options.showEasyView}">
        <canvas ref="rgEasyCanvas" style="width: 100%;height: 100%;" />
    </div>
</template>

<script lang="ts">
import { devLog } from '../../../../relation-graph-models/utils/RGCommon';

export default {
    name: 'RGEasyView',
    components: {},
    data() {
        return {
        };
    },
    inject: ['graphData', 'graph', 'graphInstance'],
    computed: {
        options() {
            return this.graph.options;
        },
        relationGraph() {
          return this.graphInstance();
        },
        allLineColors() {
            return this.graph.allLineColors;
        }
    },
    created() {
        devLog('[RGEasyView created]');
    },
    mounted() {
        devLog('[RGEasyView mounted]');
      this.relationGraph.setEasyViewCanvas && this.relationGraph.setEasyViewCanvas(this.$refs.rgEasyCanvas);
        this.init();
    },
    beforeDestroy() {
    },
    methods: {
        init() {
            // this.$refs.rgCanvas.style.setProperty('--stroke', `url('#${  this.options.instanceId  }-lineStyle')`);
            // this.$refs.rgCanvas.style.setProperty('--markerEnd', `url('#${  this.options.instanceId  }-start-arrow-default')`);
            // this.$refs.rgCanvas.style.setProperty('--markerStart', `url('#${  this.options.instanceId  }-arrow-default')`);
            // this.$refs.rgCanvas.style.setProperty('--markerEndChecked', `url('#${  this.options.instanceId  }-arrow-checked')`);
            // this.$refs.rgCanvas.style.setProperty('--markerStartChecked', `url('#${  this.options.instanceId  }-start-arrow-checked')`);
        },
    }
};
</script>
