// packages/platforms/react/src/relation-graph/src/core4react/RGGraph.tsx
import React, { useContext, useEffect, useRef } from 'react';
import SeeksRGNode from './RGNode';
import SeeksRGLink from './RGLink';
import SeeksRGLinePath from './RGLinePath';
import { RelationGraphStoreContext } from './store/reducers/StockStore';
import type { RGLineSlotProps, RGNodeSlotProps } from '../../../../../../relation-graph-models/types';
import type { MutableRefObject} from 'react';
import {RGNodeExpandHolderProps} from "../../../types-react";
import RGLineChecked from "./RGLineChecked";
import RGLineSmart from "./RGLineSmart";
export interface RGSingleGraphProps {
  nodeSlot?: React.FC<RGNodeSlotProps>
  lineSlot?: React.FC<RGLineSlotProps>
  expandHolderSlot?: React.FC<RGNodeExpandHolderProps> | JSX.Element
}
const RGSingleGraph: React.FC<RGSingleGraphProps> = (canvasProps) => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const rgCanvas$ = useRef() as MutableRefObject<HTMLDivElement>;
  useEffect(() => {
    init();
  }, []);
  const init = () => {
    rgCanvas$.current!.style.setProperty(
      '--stroke',
      `url('#${options.instanceId}-lineStyle')`
    );
    rgCanvas$.current!.style.setProperty(
      '--markerEnd',
      `url('#${options.instanceId}-start-arrow-default')`
    );
    rgCanvas$.current!.style.setProperty(
      '--markerStart',
      `url('#${options.instanceId}-arrow-default')`
    );
    rgCanvas$.current!.style.setProperty(
      '--markerEndChecked',
      `url('#${options.instanceId}-arrow-checked')`
    );
    rgCanvas$.current!.style.setProperty(
      '--markerStartChecked',
      `url('#${options.instanceId}-start-arrow-checked')`
    );
  };
  const options = relationGraph.options;
  const allLineColors = relationGraph.allLineColors;
  const nodes = relationGraph.graphData.nodes;
  const links = relationGraph.graphData.links;
  const elementLines = relationGraph.graphData.elementLines;
  return (
    <>
      <div ref={rgCanvas$} className="rel-linediv">
        <svg
          className="rel-lines-svg"
          style={
            {width: `${options.canvasSize.width  }px`,
              height: `${options.canvasSize.height  }px`}
          }
          xmlns="http://www.w3.org/2000/svg"
        >
          <defs>
            <linearGradient
              id={`${options.instanceId  }-lineStyle`}
              x1="1"
              y1="0"
              x2="0"
              y2="0"
            >
              <stop offset="0%" stopColor="#e52c5c" />
              <stop offset="100%" stopColor="#FD8B37" />
            </linearGradient>
            <marker
              id={`${options.instanceId  }-arrow-default`}
              markerWidth={options.defaultLineMarker!.markerWidth}
              markerHeight={options.defaultLineMarker!.markerHeight}
              refX={options.defaultLineMarker!.refX}
              refY={options.defaultLineMarker!.refY}
              markerUnits="userSpaceOnUse"
              orient="auto"
              viewBox="0 0 12 12"
            >
              <path
                style={{ fill: options.defaultLineColor }}
                d={options.defaultLineMarker!.data}
              />
            </marker>
            <marker
              id={`${options.instanceId  }-start-arrow-default`}
              markerWidth={options.defaultLineMarker!.markerWidth}
              markerHeight={options.defaultLineMarker!.markerHeight}
              refX={options.defaultLineMarker!.refX}
              refY={options.defaultLineMarker!.refY}
              markerUnits="userSpaceOnUse"
              orient="auto"
              viewBox="0 0 12 12"
            >
              <path
                style={{ fill: options.defaultLineColor }}
                d={options.defaultLineMarker!.data}
                transform="translate(12,12)rotate(180)"
              />
            </marker>
            <marker
              id={`${options.instanceId  }-arrow-checked`}
              markerUnits="strokeWidth"
              markerWidth="12"
              markerHeight="12"
              viewBox="0 0 12 12"
              refX="6"
              refY="6"
              orient="auto"
            >
              <path
                style={{ fill: options.checkedLineColor }}
                d="M2,2 L10,6 L2,10 L6,6 L2,2"
              />
            </marker>
            <marker
              id={`${options.instanceId  }-start-arrow-checked`}
              markerUnits="userSpaceOnUse"
              markerWidth="12"
              markerHeight="12"
              viewBox="0 0 12 12"
              refX="6"
              refY="6"
              orient="auto"
            >
              <path
                style={{ fill: options.checkedLineColor }}
                d="M2,2 L10,6 L2,10 L6,6 L2,2"
                transform="translate(12,12)rotate(180)"
              />
            </marker>
            {allLineColors.map(thisColor=>
              <marker
                id={`${options.instanceId  }-arrow-${  thisColor.id}`}
                key={thisColor.id}
                markerWidth={options.defaultLineMarker!.markerWidth}
                markerHeight={options.defaultLineMarker!.markerHeight}
                refX={options.defaultLineMarker!.refX}
                refY={options.defaultLineMarker!.refY}
                markerUnits="userSpaceOnUse"
                orient="auto"
                viewBox="0 0 12 12"
              >
                <path
                  fill={options.defaultLineMarker!.color ||
                    thisColor.color}
                  d={options.defaultLineMarker!.data}
                />
              </marker>)}
            {allLineColors.map(thisColor=>
              <marker
                id={`${options.instanceId
                }-start-arrow-${
                  thisColor.id}`}
                key={`start-${  thisColor.id}`}
                markerWidth={options.defaultLineMarker!.markerWidth}
                markerHeight={options.defaultLineMarker!.markerHeight}
                refX={options.defaultLineMarker!.refX}
                refY={options.defaultLineMarker!.refY}
                markerUnits="userSpaceOnUse"
                orient="auto"
                viewBox="0 0 12 12"
              >
                <path
                  fill={options.defaultLineMarker!.color ||
                    thisColor.color}
                  d={options.defaultLineMarker!.data}
                  transform="translate(12,12)rotate(180)"
                />
              </marker>
            )}
            {links.map(thisLink=>
              (!options.showEasyView && !thisLink.invisiable) && <React.Fragment key={thisLink.seeks_id}>
                {thisLink.relations.filter(thisRelation => (options.lineUseTextPath || thisRelation.useTextPath)).map((thisRelation, ri) =>
                  <SeeksRGLinePath
                    key = { thisRelation.id }
                    link = { thisLink }
                    relation = { thisRelation }
                    relationIndex = { ri }
                  />
                )}
              </React.Fragment>
            )}
          </defs>
          {!options.showEasyView && <RGLineChecked/>}
          {
            links.map(thisLink=>
              (!options.showEasyView && !thisLink.invisiable) && <SeeksRGLink
                key={thisLink.seeks_id}
                linkProps={thisLink}
                LineSlot={canvasProps.lineSlot}
              />
            )
          }
        </svg>
      </div>
      <div className="rel-nodediv rel-nodediv-for-webkit">
        {
          nodes.map(thisNode=>
            (!options.showEasyView && !thisNode.invisiable) && <SeeksRGNode
              key={thisNode.seeks_id}
              nodeProps={thisNode}
              NodeSlot={canvasProps.nodeSlot}
              ExpandHolderSlot={canvasProps.expandHolderSlot}
            />
          )
        }
      </div>
      <div className="rel-linediv rel-linediv-el-lines">
        <svg className="rel-lines-svg rel-lines-svg-el-lines"
             xmlns="http://www.w3.org/2000/svg">
          {
            elementLines.map(thisLink=>
              thisLink.relations[0].isHide === false && <RGLineSmart key={'ell-'+thisLink.relations[0].id} link={thisLink} relation={thisLink.relations[0]} relationIndex={0} />
            )
          }
          {
            options.creatingLinePlot && options.newLinkTemplate.fromNode
            && <RGLineSmart link={options.newLinkTemplate} relation={options.newLineTemplate} relationIndex={0} />
          }
        </svg>
      </div>
    </>
  );
};

export default RGSingleGraph;

// packages/platforms/vue2/src/core4vue/RGGraph.vue
<template>
  <div class="rel-single-graph" style="overflow: visible">
    <div ref="rgCanvas" class="rel-linediv">
      <svg class="rel-lines-svg" :style="{width : options.canvasSize.width + 'px',height: options.canvasSize.height + 'px'}" xmlns="http://www.w3.org/2000/svg">
        <defs>
          <linearGradient id="my-lineStyle" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5">
            <stop offset="0%" stop-color="#e52c5c" stop-opacity="1" />
            <stop offset="100%" stop-color="#FD8B37" stop-opacity="0" />
          </linearGradient>
          <marker
              :id="options.instanceId+'-arrow-default'"
              :markerWidth="options.defaultLineMarker.markerWidth"
              :markerHeight="options.defaultLineMarker.markerHeight"
              :refX="options.defaultLineMarker.refX"
              :refY="options.defaultLineMarker.refY"
              markerUnits="userSpaceOnUse"
              orient="auto"
              viewBox="0 0 12 12"
          >
            <path :style="{fill: options.defaultLineColor}" :d="options.defaultLineMarker.data" />
          </marker>
          <marker
              :id="options.instanceId+'-start-arrow-default'"
              :markerWidth="options.defaultLineMarker.markerWidth"
              :markerHeight="options.defaultLineMarker.markerHeight"
              :refX="options.defaultLineMarker.refX"
              :refY="options.defaultLineMarker.refY"
              markerUnits="userSpaceOnUse"
              orient="auto"
              viewBox="0 0 12 12"
          >
            <path :style="{fill: options.defaultLineColor}" :d="options.defaultLineMarker.data" transform="translate(12,12)rotate(180)"  />
          </marker>
          <marker
              :id="options.instanceId+'-arrow-checked'"
              :markerWidth="options.defaultLineMarker.markerWidth"
              :markerHeight="options.defaultLineMarker.markerHeight"
              :refX="options.defaultLineMarker.refX"
              :refY="options.defaultLineMarker.refY"
              markerUnits="userSpaceOnUse"
              orient="auto"
              viewBox="0 0 12 12"
          >
            <path :style="{fill: options.checkedLineColor}" :d="options.defaultLineMarker.data" />
          </marker>
          <marker
              :id="options.instanceId+'-start-arrow-checked'"
              :markerWidth="options.defaultLineMarker.markerWidth"
              :markerHeight="options.defaultLineMarker.markerHeight"
              :refX="options.defaultLineMarker.refX"
              :refY="options.defaultLineMarker.refY"
              markerUnits="userSpaceOnUse"
              orient="auto"
              viewBox="0 0 12 12"
          >
            <path :style="{fill: options.checkedLineColor}" :d="options.defaultLineMarker.data" transform="translate(12,12)rotate(180)" />
          </marker>
          <marker
              v-for="thisColor in allLineColors"
              :id="options.instanceId+'-arrow-'+thisColor.id"
              :key="thisColor.id"
              :markerWidth="options.defaultLineMarker.markerWidth"
              :markerHeight="options.defaultLineMarker.markerHeight"
              :refX="options.defaultLineMarker.refX"
              :refY="options.defaultLineMarker.refY"
              markerUnits="userSpaceOnUse"
              orient="auto"
              viewBox="0 0 12 12"
          >
            <path
                :fill="options.defaultLineMarker.color || thisColor.color"
                :d="options.defaultLineMarker.data"
            />
          </marker>
          <marker
              v-for="thisColor in allLineColors"
              :id="options.instanceId+'-start-arrow-'+thisColor.id"
              :key="'start-'+thisColor.id"
              :markerWidth="options.defaultLineMarker.markerWidth"
              :markerHeight="options.defaultLineMarker.markerHeight"
              :refX="options.defaultLineMarker.refX"
              :refY="options.defaultLineMarker.refY"
              markerUnits="userSpaceOnUse"
              orient="auto"
              viewBox="0 0 12 12"
          >
            <path
                :fill="options.defaultLineMarker.color || thisColor.color"
                :d="options.defaultLineMarker.data"
                transform="translate(12,12)rotate(180)"
            />
          </marker>
          <template v-if="!options.showEasyView && !thisLink.invisiable" v-for="thisLink in graphData.links">
            <template v-for="(thisRelation, ri) in thisLink.relations">
              <SeeksRGLinePath v-if="options.lineUseTextPath || thisRelation.useTextPath" :key="thisRelation.id" :link="thisLink" :relation="thisRelation" :relation-index="ri" />
            </template>
          </template>
        </defs>
        <RGLineChecked v-if="!options.showEasyView" />
        <SeeksRGLink v-if="!options.showEasyView && !thisLink.invisiable" v-for="thisLink in graphData.links" :key="thisLink.seeks_id" :link-props="thisLink">
          <template #line="{line, lineIndex}">
            <slot :line="line" :link="thisLink" :lineIndex="lineIndex" name="line" />
          </template>
        </SeeksRGLink>
      </svg>
    </div>
    <div class="rel-nodediv rel-nodediv-for-webkit">
      <SeeksRGNode v-if="!options.showEasyView && !thisNode.invisiable" v-for="thisNode in graphData.nodes" :key="thisNode.seeks_id" :node-props="thisNode">
        <template #node="{node}">
          <slot :node="node" name="node" />
        </template>
        <template #node-expand-holder="{nodeProps, expandHolderPosition, expandButtonClass, color, expandOrCollapseNode}">
          <slot
              name="node-expand-holder"
              :nodeProps="nodeProps"
              :expandHolderPosition="expandHolderPosition"
              :expandButtonClass="expandButtonClass"
              :color="color"
              :expandOrCollapseNode="expandOrCollapseNode"
          />
        </template>
      </SeeksRGNode>
    </div>
    <div class="rel-linediv rel-linediv-el-lines">
      <svg class="rel-lines-svg rel-lines-svg-el-lines" xmlns="http://www.w3.org/2000/svg">
        <template v-for="thisLink in graphData.elementLines">
          <RGLineSmart v-if="thisLink.relations[0].isHide === false" :key="'ell-'+thisLink.relations[0].id" :link="thisLink" :relation="thisLink.relations[0]" :relation-index="0" />
        </template>
        <RGLineSmart v-if="options.creatingLinePlot && options.newLinkTemplate.fromNode" key="s-line-template" :link="options.newLinkTemplate" :relation="options.newLineTemplate" :relation-index="0" />
      </svg>
    </div>
  </div>
</template>

<script lang="ts">
import SeeksRGNode from './RGNode.vue';
import SeeksRGLink from './RGLink.vue';
import SeeksRGLinePath from './RGLinePath.vue';
import RGLineSmart from './RGLineSmart.vue';
import { devLog, isSupportTouch } from '../../../../relation-graph-models/utils/RGCommon';
import RGLineChecked from "./RGLineChecked.vue";

export default {
  name: 'RelationGraphSingleGraph',
  components: {RGLineChecked, SeeksRGNode, SeeksRGLink, SeeksRGLinePath, RGLineSmart },
  data() {
    return {
    };
  },
  inject: ['graphData', 'graph', 'graphInstance'],
  computed: {
    options() {
      return this.graph.options;
    },
    relationGraph() {
      return this.graphInstance();
    },
    allLineColors() {
      return this.graph.allLineColors;
    }
  },
  created() {
    devLog('[RGGraph created]');
  },
  mounted() {
    devLog('[RGGraph mounted]');
    this.init();
  },
  beforeDestroy() {
  },
  methods: {
    init() {
      this.$refs.rgCanvas.style.setProperty('--stroke', `url('#${  this.options.instanceId  }-lineStyle')`);
      this.$refs.rgCanvas.style.setProperty('--markerEnd', `url('#${  this.options.instanceId  }-start-arrow-default')`);
      this.$refs.rgCanvas.style.setProperty('--markerStart', `url('#${  this.options.instanceId  }-arrow-default')`);
      this.$refs.rgCanvas.style.setProperty('--markerEndChecked', `url('#${  this.options.instanceId  }-arrow-checked')`);
      this.$refs.rgCanvas.style.setProperty('--markerStartChecked', `url('#${  this.options.instanceId  }-start-arrow-checked')`);
    },
  }
};
</script>
