// packages/platforms/react/src/relation-graph/src/core4react/RGLinePath.tsx
import React, {CSSProperties, useContext} from 'react';
import { RelationGraphStoreContext } from './store/reducers/StockStore';
import type { RGLineProps } from './RGLineSmart';

const RGLinePath: React.FC<RGLineProps> = ({link,relation,relationIndex}) => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const options = relationGraph.options;
  const checked = relation.id === options.checkedLineId;

  const pathData = () => {
    const { path } = relationGraph.createLinePath(
      link,
      relation,
      relationIndex
    );
    return path;
  };
  const showStartArrow = relationGraph.getArrow(relation, link, true);
  const showEndArrow = relationGraph.getArrow(relation, link, false);
  const lineWidth = relation.lineWidth !== undefined ? relation.lineWidth : (options.defaultLineWidth || 1);
  const lineColor = relation.color ? relation.color : options.defaultLineColor;
  const style:CSSProperties = options.snapshotting ? {
    stroke: lineColor,
    opacity: relation.opacity,
    strokeWidth: lineWidth + 'px',
    pointerEvents: (relation.disableDefaultClickEffect ? 'none' : undefined),
    fill: relation.lineShape === 8 ? lineColor : 'none'
  } : {};
  return (
    <path
      id={`${options.instanceId}-${relation.id}`}
      d={pathData()}
      markerStart={showStartArrow}
      markerEnd={showEndArrow}
      className={`c-rg-line-path ${relation.styleClass} ${
        checked ? 'c-rg-line-checked' : ''
      }`}
      style={style}
    />
  );
};

export default RGLinePath;

// packages/platforms/vue2/src/core4vue/RGLinePath.vue
<template>
  <path
      :id="options.instanceId + '-' + relation.id"
      :d="pathData"
      :marker-start="relationGraph.getArrow(relation, link, true)"
      :marker-end="relationGraph.getArrow(relation, link, false)"
      :class="['c-rg-line-path', relation.styleClass, checked?'c-rg-line-checked':'']"
      :style="style"
  />
</template>
<script lang="ts">
export default {
  name: 'RGLinePath',
  props: {
    link: {
      mustUseProp: true,
      default: () => { return {}; },
      type: Object
    },
    relation: {
      mustUseProp: true,
      default: () => { return {}; },
      type: Object
    },
    relationIndex: {
      mustUseProp: true,
      default: () => { return 0; },
      type: Number
    }
  },
  inject: ['graph', 'graphInstance'],
  computed: {
    checked() {
      return this.relation.id === this.options.checkedLineId;
    },
    pathData() {
      const { path, textPosition } = this.relationGraph.createLinePath(
        this.link,
        this.relation,
        this.relationIndex
      );
      return path;
    },
    options() {
      return this.graph.options;
    },
    relationGraph() {
      return this.graphInstance();
    },
    style() {
      const lineWidth = this.relation.lineWidth !== undefined ? this.relation.lineWidth : (this.options.defaultLineWidth || 1);
      const lineColor = this.relation.color ? this.relation.color : this.options.defaultLineColor;
      return this.options.snapshotting ? {
        stroke: lineColor,
        opacity: this.relation.opacity,
        strokeWidth: lineWidth + 'px',
        pointerEvents: (this.relation.disableDefaultClickEffect ? 'none' : undefined),
        fill: this.relation.lineShape === 8 ? lineColor : 'none'
      } : {};
    }
  },
  data() {
    return {
      is_flashing: false
    };
  },
  show() {
    this.isShow = true;
  },
  methods: {
  }
};
</script>
