// packages/platforms/react/src/relation-graph/src/core4react/RGLineChecked.tsx
import React, { useContext } from 'react';
import { RelationGraphStoreContext } from './store/reducers/StockStore';

const RGLineChecked: React.FC = () => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const pathData = relationGraph.createCheckedLinePath();
  const strokeWidth = relationGraph.createCheckedLineStrokeWidth();
  return (
    <g>
      {pathData && <path
        d={pathData}
        fill="none"
        stroke="red"
        strokeWidth={strokeWidth}
        className="c-rg-line-checked-bg"
      />}
    </g>
  );
};

export default RGLineChecked;

// packages/platforms/vue2/src/core4vue/RGLineChecked.vue
<template>
  <g>
    <path
        v-if="pathData"
        :d="pathData"
        fill="none"
        stroke="red"
        :stroke-width="strokeWidth"
        class="c-rg-line-checked-bg"
    />
  </g>
</template>

<script lang="ts">

import {devLog} from "../../../../relation-graph-models/utils/RGCommon";
import {RGLine, RGLink} from "../../../../relation-graph-models/types";

export default {
  name: 'RGLineChecked',
  inject: ['graph', 'graphInstance'],
  computed: {
    options() {
      return this.graph.options;
    },
    relationGraph() {
      return this.graphInstance();
    },
    pathData() {
      return this.relationGraph.createCheckedLinePath();
    },
    strokeWidth() {
      return this.relationGraph.createCheckedLineStrokeWidth();
    }
  },
  data() {
    return {
      is_flashing: false
    };
  },
  show() {
    this.isShow = true;
  },
  watch: {
  }
};
</script>

<style scoped>
</style>
