// packages/platforms/react/src/relation-graph/src/core4react/RGNode.tsx
import React, {MutableRefObject, useContext, useEffect, useRef} from 'react';
import RGNodesAnalytic from '../../../../../../relation-graph-models/utils/RGNodesAnalytic';
import { RGUpdateContext, RelationGraphStoreContext } from './store/reducers/StockStore';
import RGNodeExpandHolder from './RGNodeExpandHolder';
import {RGNodeProps} from '../../../types-react';

const SeeksRGNode: React.FC<RGNodeProps> = ({nodeProps, NodeSlot, ExpandHolderSlot}) => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const updateView = useContext(RGUpdateContext);
  const seeksRGNodeRef = useRef() as MutableRefObject<HTMLDivElement>;
  useEffect(() => {
    refreshNodeProperties(seeksRGNodeRef.current);
    relationGraph.addNodeResizeListener(seeksRGNodeRef.current, nodeProps);
    return () => {
      // console.log('卸载：', nodeProps.id);
      seeksRGNodeRef.current && relationGraph.removeNodeResizeListener(seeksRGNodeRef.current);
    };
  }, []);
  // const seeksRGNodeRef = useCallback((seeksRGNodeEl:HTMLDivElement) => {
  //   if (seeksRGNodeEl!==null) {
  //     refreshNodeProperties(seeksRGNodeEl);
  //   }
  // }, []);



  const refreshNodeProperties = (seeksRGNodeEl:HTMLDivElement) => {
    if (
      seeksRGNodeEl.offsetWidth === 0 &&
      seeksRGNodeEl.offsetHeight === 0
    ) {
      return;
    }

    const elWidth = seeksRGNodeEl.offsetWidth;
    const elHeight = seeksRGNodeEl.offsetHeight;

    if (
      nodeProps.el.offsetWidth !== elWidth ||
      nodeProps.el.offsetHeight !== elHeight
    ) {
      // console.log('updateNodeOffsetSize：', nodeProps.el.offsetWidth, nodeProps.el.offsetHeight, ' > ', elWidth, elHeight);
      relationGraph.updateNodeOffsetSize(nodeProps, elWidth, elHeight);
      updateView();
    }
  };

  const expandOrCollapseNode = async (e: React.MouseEvent|React.TouchEvent) => {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    await relationGraph.expandOrCollapseNode(nodeProps, e);
  };

  const onDragStart = (e :React.MouseEvent|React.TouchEvent) => {
    if (e.type === "mousedown" && e.button !== 0) {
      return;
    }
    e.stopPropagation();
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    relationGraph.onNodeDragStart(nodeProps, e);
  };

  const onNodeClick = (e :React.MouseEvent|React.TouchEvent) => {
    e.stopPropagation();
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    relationGraph.onNodeClick(nodeProps, e);
  };


  const options = relationGraph.options;
  const width = nodeProps.width || options.defaultNodeWidth;
  const height = nodeProps.height || options.defaultNodeHeight;
  // const borderStyle = `${nodeProps.borderColor || options.defaultNodeBorderColor} solid ${nodeProps.borderWidth === undefined ? options.defaultNodeBorderWidth : nodeProps.borderWidth}px`;
  const _bw = nodeProps.borderWidth === undefined ? options.defaultNodeBorderWidth : nodeProps.borderWidth;
  const borderWidth = !_bw ? undefined : (_bw + 'px');
  const borderColor = nodeProps.borderColor || options.defaultNodeBorderColor;
  const hideNodeContent = !(
    options.hideNodeContentByZoom === true &&
    options.canvasZoom! < 40
  );
  const opacity = nodeProps.opacity === undefined ? 1 : (nodeProps.opacity > 1 ? nodeProps.opacity / 100 : nodeProps.opacity);
  const showNode = RGNodesAnalytic.isAllowShowNode(nodeProps);
  const showExpandHolder = (nodeProps.expandHolderPosition && nodeProps.expandHolderPosition !== 'hide') ||
    (options.defaultExpandHolderPosition &&
      options.defaultExpandHolderPosition !== 'hide' &&
      nodeProps.lot.childs &&
      nodeProps.lot.childs.length > 0);
  const expandButtonClass = nodeProps.expanded === false ? 'c-expanded' : 'c-collapsed';
  return (
    <div
      ref={seeksRGNodeRef}
      style={{
        display: showNode ? undefined : 'none',
        zIndex:nodeProps.zIndex ? nodeProps.zIndex : undefined,
        left: nodeProps.x + 'px',
        top: nodeProps.y + 'px',
        opacity: opacity,
        pointerEvents: opacity === 0 ? 'none' : undefined
      }}
      className={`rel-node-peel ${nodeProps.selected ? 'rel-node-selected' : ''} ${nodeProps.dragging ? 'rel-node-dragging' : ''} ${nodeProps.id===options.checkedNodeId ? 'rel-node-peel-checked' : ''} ${nodeProps.className ?? nodeProps.className}`}
      data-id={nodeProps.id}
    >
      { showExpandHolder &&
        (
          ExpandHolderSlot ?
            (
              typeof ExpandHolderSlot === 'function' ?
                <ExpandHolderSlot
                  nodeProps={nodeProps}
                  expandButtonClass={expandButtonClass}
                  expandOrCollapseNode={($event: React.MouseEvent|React.TouchEvent) => {expandOrCollapseNode($event);}}
                  expandHolderPosition={nodeProps.expandHolderPosition||options.defaultExpandHolderPosition}
                  color={options.defaultExpandHolderColor||nodeProps.color||options.defaultNodeColor}
                />
                : ExpandHolderSlot
            )
            :
            <RGNodeExpandHolder
              nodeProps={nodeProps}
              expandButtonClass={expandButtonClass}
              expandOrCollapseNode={($event: React.MouseEvent|React.TouchEvent) => {expandOrCollapseNode($event);}}
              expandHolderPosition={nodeProps.expandHolderPosition||options.defaultExpandHolderPosition}
              color={options.defaultExpandHolderColor||nodeProps.color||options.defaultNodeColor}
            />
        )
      }
      {nodeProps.html ? (
        <div
          onClick={(e)=>{onNodeClick(e);}}
          onMouseDown={(e)=>{onDragStart(e);}}
          onTouchStart={(e)=>{onDragStart(e);}}
          dangerouslySetInnerHTML={{__html:nodeProps.html!}}
        ></div>
      ) : (
        <div
          className={`rel-node rel-node-shape-${nodeProps.nodeShape === undefined ? options.defaultNodeShape : nodeProps.nodeShape} rel-node-type-${nodeProps.type} ${
            nodeProps.id === options.checkedNodeId ? 'rel-node-checked' : ''
          } ${nodeProps.flashing ? 'rel-node-flashing' : ''} ${nodeProps.styleClass} ${nodeProps.innerHTML ? 'rel-diy-node' : ''}`}
          style={{
            backgroundColor: nodeProps.color === undefined ? options.defaultNodeColor : nodeProps.color,
            color: nodeProps.fontColor === undefined ? options.defaultNodeFontColor : nodeProps.fontColor,
            borderWidth: borderWidth,
            borderColor: borderColor,
            width: width && `${width}px`,
            height: height && `${height}px`
          }}
          onClick={(e)=>{onNodeClick(e);}}
          onMouseDown={(e)=>{onDragStart(e);}}
          onTouchStart={(e)=>{onDragStart(e);}}
        >
          {
            hideNodeContent &&
              <>
                {
                  NodeSlot ? <NodeSlot node={nodeProps} relationGraph={relationGraph} /> :
                    <>
                      {!nodeProps.innerHTML ? <div
                        style={{ color: nodeProps.fontColor || options.defaultNodeFontColor }}
                        className="c-node-text"
                      >
                          <span>{nodeProps.text}</span>
                      </div>
                        :
                        <div dangerouslySetInnerHTML={{__html: nodeProps.innerHTML!}} />}
                    </>
                }
              </>
          }
        </div>
      )}
    </div>
  );
};

export default SeeksRGNode;

// packages/platforms/vue2/src/core4vue/RGNode.vue
<template>
  <div
    v-show="isAllowShowNode"
    ref="seeksRGNode"
    :style="{
      'left':nodeProps.x + 'px',
      'top':nodeProps.y + 'px',
      'z-index':nodeProps.zIndex ? nodeProps.zIndex : undefined,
      'opacity': (nodeProps.opacity>1?nodeProps.opacity/100:nodeProps.opacity),
       'pointer-events': nodeProps.opacity === 0 ? 'none' : undefined
    }"
    class="rel-node-peel"
    :class="[
      (nodeProps.selected && 'rel-node-selected'),
      (nodeProps.dragging && 'rel-node-dragging'),
      (nodeProps.id===options.checkedNodeId && 'rel-node-peel-checked'),
      nodeProps.className
      ]"
    :data-id="nodeProps.id"
  >
    <template v-if="showExpandHolder">
      <template v-if="options.oldVueVersion && !options.ovUseNodeExpandHolderSlot">
        <RGNodeExpandHolder
            :nodeProps="nodeProps"
            :expandButtonClass="expandButtonClass"
            :expandOrCollapseNode="expandOrCollapseNode"
            :expandHolderPosition="(nodeProps.expandHolderPosition||options.defaultExpandHolderPosition)"
            :color="(options.defaultExpandHolderColor||nodeProps.color||options.defaultNodeColor)"
        />
      </template>
      <slot
          v-else
          name="node-expand-holder"
          :nodeProps="nodeProps"
          :expandButtonClass="expandButtonClass"
          :expandOrCollapseNode="expandOrCollapseNode"
          :expandHolderPosition="(nodeProps.expandHolderPosition||options.defaultExpandHolderPosition)"
          :color="(options.defaultExpandHolderColor||nodeProps.color||options.defaultNodeColor)"
      >
        <RGNodeExpandHolder
            :nodeProps="nodeProps"
            :expandButtonClass="expandButtonClass"
            :expandOrCollapseNode="expandOrCollapseNode"
            :expandHolderPosition="(nodeProps.expandHolderPosition||options.defaultExpandHolderPosition)"
            :color="(options.defaultExpandHolderColor||nodeProps.color||options.defaultNodeColor)"
        />
      </slot>
    </template>
    <div
        v-if="nodeProps.html"
        v-html="nodeProps.html"
        @click="onclick($event)"
        @mousedown.left.stop="onDragStart($event)"
        @touchstart.stop="onDragStart($event)"
    />
    <div
      v-else
      :class="['rel-node-shape-'+(nodeProps.nodeShape===undefined?options.defaultNodeShape:nodeProps.nodeShape),'rel-node-type-'+nodeProps.type, (nodeProps.id===options.checkedNodeId?'rel-node-checked':''), (nodeProps.flashing?'rel-node-flashing':''), nodeProps.styleClass, (nodeProps.innerHTML?'rel-diy-node':'')]"
      :style="{'background-color':(nodeProps.color===undefined?options.defaultNodeColor:nodeProps.color),'color':(nodeProps.fontColor===undefined?options.defaultNodeFontColor:nodeProps.fontColor),'border-color': borderColor, 'border-width': borderWidth, 'width': nodeWidth, 'height':nodeHeight}"
      class="rel-node"
      @click="onclick($event)"
      @mousedown.left.stop="onDragStart($event)"
      @touchstart.stop="onDragStart($event)"
    >
      <template v-if="!(options.hideNodeContentByZoom === true && options.canvasZoom<40)">
        <template v-if="options.oldVueVersion && !options.ovUseNodeSlot">
          <div v-if="!nodeProps.innerHTML" :style="{'color':(nodeProps.fontColor || options.defaultNodeFontColor)}" class="c-node-text">
            <span v-html="nodeProps.text" />
          </div>
          <div v-else v-html="nodeProps.innerHTML" />
        </template>
        <slot v-else name="node" :node="nodeProps">
          <div v-if="!nodeProps.innerHTML" :style="{'color':(nodeProps.fontColor || options.defaultNodeFontColor)}" class="c-node-text">
            <span v-html="nodeProps.text" />
<!--            {{options.defaultExpandHolderPosition + ''}} /-->
<!--            {{nodeProps.expandHolderPosition + ''}}-->
<!--            {{(nodeProps.lot.childs && nodeProps.lot.childs.length) + ''}}-->
          </div>
          <div v-else v-html="nodeProps.innerHTML" />
        </slot>
      </template>
    </div>
  </div>
</template>

<script lang="ts">
import { devLog } from '../../../../relation-graph-models/utils/RGCommon';
import {RGNodesAnalytic} from "../../../../relation-graph-models/utils/RGNodesAnalytic";
import RGNodeExpandHolder from "./RGNodeExpandHolder.vue";



export default {
  name: 'RGNode',
  components: {RGNodeExpandHolder},
  props: {
    nodeProps: {
      mustUseProp: true,
      default: () => { return {}; },
      type: Object
    }
  },
  data() {
    return {
      expanding: false
    };
  },
  inject: ['graph', 'graphInstance'],
  computed: {
    oldVersionSlot() {
      const slot = this.$scopedSlots['node'](({ node: this.nodeProps }));
      if (slot.length === 0) {
        return null;
      }
      return slot;
    },
    expandButtonClass() {
      return this.nodeProps.expanded === false ? 'c-expanded' : 'c-collapsed';
    },
    showExpandHolder() {
      if (this.nodeProps.expandHolderPosition && this.nodeProps.expandHolderPosition !== 'hide') {
        return true;
      }
      if (this.nodeProps.lot.childs && this.nodeProps.lot.childs.length > 0) {
        if (this.options.defaultExpandHolderPosition && this.options.defaultExpandHolderPosition !== 'hide') {
          return true;
        }
      } else {
        return false;
      }
    },
    options() {
      return this.graph.options;
    },
    relationGraph() {
      return this.graphInstance();
    },
    borderColor() {
      return this.nodeProps.borderColor || this.options.defaultNodeBorderColor
    },
    borderWidth() {
      const width = this.nodeProps.borderWidth === undefined ? this.options.defaultNodeBorderWidth : this.nodeProps.borderWidth;
      return !width ? undefined : (width + 'px');
    },
    nodeWidth() {
      if (this.nodeProps.width === 0) return;
      const v = this.nodeProps.width || this.options.defaultNodeWidth
      if (!v) {
        return;
      }
      return v+'px'
    },
    nodeHeight() {
      if (this.nodeProps.height === 0) return;
      const v = this.nodeProps.height||this.options.defaultNodeHeight
      if (!v) {
        return;
      }
      return v+'px'
    },
    isAllowShowNode() {
      return RGNodesAnalytic.isAllowShowNode(this.nodeProps);
    }
  },
  created() {
    // Vue.version
  },
  mounted() {
    this.refreshNodeProperties();
    // this.leave(this.$refs.seeksRGNode)
    this.relationGraph.addNodeResizeListener(this.$refs.seeksRGNode, this.nodeProps);
    devLog('RGNode:mounted');
  },
  // updated() {
  //   // this.refreshNodeProperties();
  //   // console.log('xxxxxxxxxxxxxxxxxxxxxxxxx:refreshNodeProperties');
  // },
  beforeDestroy() {
    // const elx = this.$refs.seeksRGNode;
    // elx.remove();
    this.relationGraph.removeNodeResizeListener(this.$refs.seeksRGNode);
  },
  methods: {
    refreshNodeProperties() {
      if (this.$refs.seeksRGNode.offsetWidth === 0 && this.$refs.seeksRGNode.offsetHeight === 0) {
        return;
      }
      if (this.nodeProps.el.offsetWidth !== this.$refs.seeksRGNode.offsetWidth || this.nodeProps.el.offsetHeight !== this.$refs.seeksRGNode.offsetHeight) {
        this.relationGraph.updateNodeOffsetSize(this.nodeProps, this.$refs.seeksRGNode.offsetWidth, this.$refs.seeksRGNode.offsetHeight);
      }
    },
    async expandOrCollapseNode(e) {
      devLog('expandOrCollapseNode', this.expanding);
      if (this.expanding) {
        return;
      }
      this.expanding = true;
      setTimeout(() => { // 防止手太快或者手表太灵敏
        this.expanding = false;
      }, 300);
      await this.relationGraph.expandOrCollapseNode(this.nodeProps, e);
    },
    onDragStart(e) {
      this.relationGraph.onNodeDragStart(this.nodeProps, e);
    },
    onclick(e) {
      this.relationGraph.onNodeClick(this.nodeProps, e);
    }
  }
};
</script>

<style scoped>
</style>
