// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGEasyView.vue
<script lang="ts" setup>
import { computed, inject, onMounted, ref } from 'vue'
import { devLog } from '../../../../../../relation-graph-models/utils/RGCommon'
import {graphInstanceKey, graphKey} from '../../../constants'
const $rgEasyCanvas = ref<HTMLCanvasElement>()
// const graphInstance$ = inject(graphInstanceKey)
const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})
onMounted(() => {
  devLog('[RGEasyView mounted]');
  graph.instance!.setEasyViewCanvas && graph.instance!.setEasyViewCanvas($rgEasyCanvas.value!);
})
</script>
<template>
    <div class="rel-easy-view" :class="{'rel-easy-view-active':options.showEasyView}">
        <canvas ref="$rgEasyCanvas" style="width: 100%;height: 100%;" />
    </div>
</template>

// packages/platforms/react/src/relation-graph/src/core4react/RGEasyView.tsx
import React, {MutableRefObject, useContext, useEffect, useRef} from 'react';
import {RelationGraphStoreContext} from './store/reducers/StockStore';
import {RGCanvasProps} from './RGCanvas';
import { devLog } from '../../../../../../relation-graph-models/utils/RGCommon';

const RGCanvas: React.FC<RGCanvasProps> = (canvasProps) => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const options = relationGraph.options;
  const rgEasyCanvas$ = useRef() as MutableRefObject<HTMLCanvasElement>;

  useEffect(() => {
    devLog('[RGEasyView mounted]');
    relationGraph.setEasyViewCanvas(rgEasyCanvas$.current!);
  }, []);

  return (
    <div className={`rel-easy-view ${options.showEasyView ? 'rel-easy-view-active' : ''}`}>
      <canvas ref={rgEasyCanvas$} />
    </div>
  );
};

export default RGCanvas;
