// packages/platforms/vue2/src/core4vue/RGNodeExpandHolder.vue
<template>
  <div :class="[('c-expand-positon-' + expandHolderPosition)]" class="c-btn-open-close">
    <span
        :class="expandButtonClass"
        :style="{ 'background-color': color }"
        @click.stop="expandOrCollapseNode"
        @touchend.stop="expandOrCollapseNode"
    >
    </span>
  </div>
</template>

<script lang="ts">
export default {
  name: 'RGNodeExpandHolder',
  props: {
    nodeProps: {
      type: Object,
      required: true
    },
    expandButtonClass: {
      type: String,
      required: true
    },
    expandOrCollapseNode: {
      type: Function,
      required: true
    },
    expandHolderPosition: {
      type: String,
      required: true
    },
    color: {
      type: String,
      required: true
    }
  }
}
</script>

// packages/platforms/react/src/relation-graph/src/core4react/RGNodeExpandHolder.tsx
import React from 'react';
import {RGNodeExpandHolderProps} from "../../../types-react";

const RGNodeExpandHolder: React.FC<RGNodeExpandHolderProps> = ({expandButtonClass, expandOrCollapseNode, expandHolderPosition, color}) => {
  return (
    <div
      className={`c-expand-positon-${expandHolderPosition} c-btn-open-close`}
    >
      <span
        className={expandButtonClass}
        style={{ backgroundColor: color }}
        onClickCapture={(e) => {
          expandOrCollapseNode(e);
        }}
        onTouchEnd={(e) => {
          expandOrCollapseNode(e);
        }}
      ></span>
    </div>
  );
};

export default RGNodeExpandHolder;
