// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGNodeExpandHolder.vue
<script lang="ts" setup>
import type { RGNode } from '../../../../../../relation-graph-models/types';
const props = defineProps<{
  nodeProps: RGNode
  expandButtonClass: string
  expandOrCollapseNode: (e: MouseEvent) => void
  expandHolderPosition: string
  color: string
}>()
</script>
<template>
  <div
      :class="[('c-expand-positon-'+expandHolderPosition)]"
      class="c-btn-open-close"
  >
      <span
          :class="expandButtonClass" :style="{'background-color':color}"
          @click.stop="expandOrCollapseNode"
          @touchend.stop="expandOrCollapseNode"
      >
      </span>
  </div>
</template>

// packages/platforms/react/src/relation-graph/src/core4react/RGNodeExpandHolder.tsx
import React from 'react';
import {RGNodeExpandHolderProps} from "../../../types-react";

const RGNodeExpandHolder: React.FC<RGNodeExpandHolderProps> = ({expandButtonClass, expandOrCollapseNode, expandHolderPosition, color}) => {
  return (
    <div
      className={`c-expand-positon-${expandHolderPosition} c-btn-open-close`}
    >
      <span
        className={expandButtonClass}
        style={{ backgroundColor: color }}
        onClickCapture={(e) => {
          expandOrCollapseNode(e);
        }}
        onTouchEnd={(e) => {
          expandOrCollapseNode(e);
        }}
      ></span>
    </div>
  );
};

export default RGNodeExpandHolder;
