// relation-graph-react/src/relation-graph/src/core4react/RGLink.tsx
import React, {useContext, useEffect} from 'react';
import RGLineSmart from './RGLineSmart';
import RGLineTextByPath from './RGLineTextByPath';
import RGNodesAnalytic from '../../../../../relation-graph-vue2/src/utils/RGNodesAnalytic';
import {RelationGraphStoreContext} from './store/reducers/StockStore';
import type { RGLink, RGNode, RGLineSlotProps } from '../../../../../relation-graph-vue2/src/types';
export interface RGLinkProps {
  linkProps: RGLink
  LineSlot?: React.FC<RGLineSlotProps>
}
const SeeksRGLink = ({ linkProps, LineSlot }:RGLinkProps) => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const isAllowShowNode = (thisNode:RGNode) => {
    return RGNodesAnalytic.isAllowShowNode(thisNode);
  };

  useEffect(() => {
    // mounted logic here
  }, []);

  const options = relationGraph.options;
  return (
    <g
      style={{ display: isAllowShowNode(linkProps.fromNode) && isAllowShowNode(linkProps.toNode) ? 'block' : 'none' }}
      className={[
        'rel-link-peel',
        options.checkedLineId === linkProps.seeks_id ? 'c-rg-link-checked' : ''
      ].join(' ')}
      transform="translate(0,0)"
      data-id={linkProps.seeks_id}
    >
      {linkProps.relations.map((thisRelation, ri) =>
        <React.Fragment key={thisRelation.id}>
          {
            LineSlot ?
              <LineSlot relationGraph={relationGraph} link={linkProps} relation={thisRelation} relationIndex={ri}  />
              :
              (
                (thisRelation.useTextPath || options.lineUseTextPath) ?
                  <RGLineTextByPath link={linkProps} relation={thisRelation} relationIndex={ri} />
                  :
                  <RGLineSmart link={linkProps} relation={thisRelation} relationIndex={ri} />
              )
          }
        </React.Fragment>
      )}
    </g>
  );
};

export default SeeksRGLink;

// relation-graph-vue3/src/relation-graph/src/core4vue3/RGLink.vue
<script lang="ts" setup>
import {computed, inject} from 'vue'
import {graphInstanceKey, graphKey} from '../../../constants'
import RGLineTextByPath from './RGLineTextByPath.vue'
import RGLineSmart from './RGLineSmart.vue'
import RGNodesAnalytic from '../../../../../relation-graph-vue2/src/utils/RGNodesAnalytic'
import type { RGLink, RGNode } from '../../../../../relation-graph-vue2/src/types';
const props = defineProps<{
  linkProps: RGLink
}>()
const graphInstance$ = inject(graphInstanceKey)
const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})
const isAllowShowNode = (thisNode:RGNode):boolean => {
  return RGNodesAnalytic.isAllowShowNode(thisNode);
}
</script>
<template>
  <g
      v-if="linkProps.isHide !== true && isAllowShowNode(linkProps.fromNode) && isAllowShowNode(linkProps.toNode)"
      :class="[options.checkedLineId==linkProps.seeks_id?'c-rg-link-checked':'']"
      ref="seeksRGLink"
      transform="translate(0,0)"
      class="rel-link-peel"
      :data-id="linkProps.seeks_id"
  >
    <template v-for="(thisRelation, ri) in linkProps.relations">
      <slot name="line" :line="thisRelation" :relation-index="ri">
        <RGLineTextByPath v-if="(options.lineUseTextPath || thisRelation.useTextPath) && thisRelation.isHide === false" :key="'l-'+thisRelation.id" :link="linkProps" :relation="thisRelation" :relation-index="ri" />
        <RGLineSmart v-else-if="thisRelation.isHide === false" :key="'l-'+thisRelation.id" :link="linkProps" :relation="thisRelation" :relation-index="ri" />
      </slot>
    </template>
  </g>
</template>
