// relation-graph-vue3/src/relation-graph/src/core4vue3/RGLineTextByPath.vue
<script lang="ts" setup>
import { computed, inject } from 'vue'
import { getTextSize } from '../../../../../relation-graph-vue2/src/utils/RGCommon'
import { getNodeDistance } from '../../../../../relation-graph-vue2/src/utils/RGGraphMath'
import {graphInstanceKey, graphKey} from '../../../constants'
import type { RGLine, RGLink } from '../../../../../relation-graph-vue2/src/types';
const props = defineProps<{
  link: RGLink
  relation: RGLine
  relationIndex: number
}>()
const graphInstance$ = inject(graphInstanceKey)
const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})
const checked = computed(() => {
  return props.link.seeks_id === graphInstance$?.value!.options.checkedLineId
})
const textOffset = computed(() => {
  const x = props.relation.textOffset_x || options.value.defaultLineTextOffset_x || 0;
  const y = props.relation.textOffset_y || options.value.defaultLineTextOffset_y || -8;
  return `translate(${x},${y})`
})
const pathRef = computed(() => {
  return '#' + options.value.instanceId + '-' +  props.link.seeks_id + '-' + props.relationIndex;
})
const textAnchor = computed(() => {
  if (props.relation.lineShape === 4 || options.value.defaultLineShape === 4) {
    return 'start';
  }
  return 'middle';
})
const textHPosition = computed(() => {
  if (props.relation.lineShape === 4 || options.value.defaultLineShape === 4) {
    if (options.value.layoutDirection === 'v') {
      const fx = props.link.fromNode.x;
      const tx = props.link.toNode.x;
      return Math.abs(tx - fx) + 43;
    } else {
      const fy = props.link.fromNode.y;
      const ty = props.link.toNode.y;
      return Math.abs(ty - fy) + 43;
    }
  }
  return '50%';
})

const onClick = (line:RGLine, e:MouseEvent|TouchEvent) => {
  graphInstance$?.value!.onLineClick(line, props.link, e)
}
</script>
<template>
  <g>
    <use
        :xlink:href="pathRef"
        class="c-rg-line"
        :class="[
            relation.styleClass,
            relation.dashType ? ('rg-line-dashtype-' + relation.dashType) : undefined,
            relation.animation ? ('rg-line-anm-' + relation.animation) : undefined,
            checked ? 'c-rg-line-checked' : undefined
        ]"
        @touchstart.stop="onClick(relation, $event)"
        @click="onClick(relation, $event)" />
    <g
        :transform="textOffset"
    >
      <text
          class="c-rg-line-text"
          :style="{
            opacity: relation.opacity,
            fill:(relation.fontColor?relation.fontColor:(options.defaultLineFontColor ? options.defaultLineFontColor : (relation.color?relation.color:options.defaultLineColor)))
          }"
          @touchstart.stop="onClick(relation, $event)"
          @click="onClick(relation, $event)"
      >
        <textPath :xlink:href="pathRef" :startOffset="textHPosition" :text-anchor="textAnchor" method="align" spacing="auto"> {{ relation.text }} </textPath>
      </text>
    </g>
  </g>
</template>

// relation-graph-react/src/relation-graph/src/core4react/RGLineTextByPath.tsx
import React, { useContext } from 'react';
import { RGUpdateContext, RelationGraphStoreContext } from './store/reducers/StockStore';
import type { RGLineProps } from './RGLineSmart';

const RGLineTextByPath: React.FC<RGLineProps> = ({link,relation, relationIndex}) => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const updateView = useContext(RGUpdateContext);
  const options = relationGraph.options;
  const textOffset = `translate(${relation.textOffset_x || options.defaultLineTextOffset_x || 0},${relation.textOffset_y || options.defaultLineTextOffset_y || -8})`;
  const pathRef = `#${options.instanceId}-${link.seeks_id}-${relationIndex}`;
  const checked = link.seeks_id === options.checkedLineId;
  const textAnchor = relation.lineShape === 4 || options.defaultLineShape === 4 ? 'start' : 'middle';
  const textHPosition = relation.lineShape === 4 || options.defaultLineShape === 4 ? (options.layoutDirection === 'v' ? Math.abs(link.toNode.x - link.fromNode.x) + 43 : Math.abs(link.toNode.y - link.fromNode.y) + 43) : '50%';

  const onClick = (e: React.MouseEvent|React.TouchEvent) => {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    relationGraph.onLineClick(relation, link, e);
    updateView();
  };

  return (
    <g>
      <use
        xlinkHref={pathRef}
        className={[
          'c-rg-line',
          relation.styleClass,
          relation.dashType ? `rg-line-dashtype-${relation.dashType}` : undefined,
          relation.animation ? `rg-line-anm-${relation.animation}` : undefined,
          checked ? 'c-rg-line-checked' : undefined
        ].filter(Boolean).join(' ')}
        onTouchStart={(e) => onClick(e)}
        onClick={(e) => onClick(e)}
      />
      <g transform={textOffset}>
        <text
          className="c-rg-line-text"
          style={{
            opacity: relation.opacity,
            fill: relation.fontColor || options.defaultLineFontColor || relation.color || options.defaultLineColor
          }}
          onTouchStart={(e) => onClick(e)}
          onClick={(e) => onClick(e)}
        >
          <textPath xlinkHref={pathRef} startOffset={textHPosition} textAnchor={textAnchor} method="align" spacing="auto">{relation.text}</textPath>
        </text>
      </g>
    </g>
  );
};

export default RGLineTextByPath;
