// relation-graph-vue3/src/relation-graph/src/core4vue3/RGLineSmart.vue
<script lang="ts" setup>
import { computed, inject, onMounted, onUpdated, ref } from 'vue'
import {graphInstanceKey, graphKey} from '../../../constants'
import { devLog } from '../../../../../relation-graph-vue2/src/utils/RGCommon';
import type { RGLine, RGLink } from '../../../../../relation-graph-vue2/src/types';

const props = defineProps<{
  link: RGLink
  relation: RGLine
  relationIndex: number
}>()
const graphInstance$ = inject(graphInstanceKey)
const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})
const checked = computed(() => {
  return props.link.seeks_id === options.value.checkedLineId
})
const showStartArrow = computed(() => {
  return props.relation.showStartArrow && graphInstance$?.value!.getArrow(props.relation, props.link, true);
})
const showEndArrow = computed(() => {
  return props.relation.showEndArrow && graphInstance$?.value!.getArrow(props.relation, props.link, false);
})
const pathData = computed(() => {
  try {
    const { path, textPosition } = graphInstance$?.value!.createLinePath(
        props.link,
        props.relation,
        props.relationIndex
    );
    let textTransform = {}
    try {
      textTransform = graphInstance$?.value!.getTextTransform(
          props.relation,
          textPosition.x,
          textPosition.y,
          textPosition.rotate
      )
    } catch (e) {
      devLog(e);
    }
    return {
      path,
      textTransform
    };
  } catch (e) {
    devLog(e);
  }
  return {path:null, textTransform: null};
})
const onClick = (line:RGLine, e: MouseEvent | TouchEvent) => {
  graphInstance$?.value!.onLineClick(line, props.link, e)
}
</script>
<template>
  <g>
    <!-- 常规方式 -->
    <path
        :d="pathData.path"
        class="c-rg-line"
        :class="[
            relation.styleClass,
            relation.dashType ? ('rg-line-dashtype-' + relation.dashType) : undefined,
            relation.animation ? ('rg-line-anm-' + relation.animation) : undefined,
            checked ? 'c-rg-line-checked' : undefined
        ]"
        :stroke="
        (relation.color?relation.color:options.defaultLineColor)
      "
        :style="{
        'opacity': relation.opacity,
        'stroke-width':
          (relation.lineWidth
            ? relation.lineWidth
            : options.defaultLineWidth) + 'px',
      }"
        :marker-start="showStartArrow"
        :marker-end="showEndArrow"
        fill="none"
        @touchstart.stop="onClick(relation, $event)"
        @click="onClick(relation, $event)"
    />
    <g
        v-if="
        options.defaultShowLineLabel &&
        options.canvasZoom > 40
      "
        :transform="pathData.textTransform"
    >
      <text
          :key="'t-' + relation.seeks_id"
          :x="relation.textOffset_x || options.defaultLineTextOffset_x || 0"
          :y="relation.textOffset_y || options.defaultLineTextOffset_y || 10"
          :style="{
          opacity: relation.opacity,
          fill: (relation.fontColor?relation.fontColor:(options.defaultLineFontColor ? options.defaultLineFontColor : (relation.color?relation.color:options.defaultLineColor)))
        }"
          class="c-rg-line-text"
          @touchstart.stop="onClick(relation, $event)"
          @click="onClick(relation, $event)"
      >
        {{ relation.text }}
      </text>
    </g>
  </g>
</template>

// relation-graph-react/src/relation-graph/src/core4react/RGLineSmart.tsx
import React, { useContext } from 'react';
import { RGUpdateContext, RelationGraphStoreContext } from './store/reducers/StockStore';
import type { RGLine, RGLink } from '../../../../../relation-graph-vue2/src/types';
import { devLog } from '../../../../../relation-graph-vue2/src/utils/RGCommon';
export interface RGLineProps {
  link: RGLink
  relation: RGLine
  relationIndex: number
}
const RGLineSmart: React.FC<RGLineProps> = ({link,relation,relationIndex}) => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const updateView = useContext(RGUpdateContext);
  const options = relationGraph.options;
  const checked = link.seeks_id === options.checkedLineId;

  const showStartArrow = relation.showStartArrow ? relationGraph.getArrow(relation, link, true) : undefined;
  const showEndArrow = relation.showEndArrow ? relationGraph.getArrow(relation, link, false) : undefined;

  const pathData = React.useMemo(() => {
    try {
      const { path, textPosition } = relationGraph.createLinePath(link, relation, relationIndex);
      let textTransform = undefined;
      try {
        textTransform = relationGraph.getTextTransform(relation, textPosition.x, textPosition.y, textPosition.rotate);
      } catch (e) {
        devLog(e);
      }
      return {
        path,
        textTransform
      };
    } catch (e) {
      devLog(e);
    }
    return { path: undefined, textTransform: undefined };
  }, [link, relation, relationIndex]);

  const onClick = (e: React.MouseEvent|React.TouchEvent) => {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    relationGraph.onLineClick(relation, link, e);
    updateView();
  };

  return (
    <g>
      <path
        d={pathData.path}
        className={[
          'c-rg-line',
          relation.styleClass,
          relation.dashType ? ('rg-line-dashtype-' + relation.dashType) : undefined,
          relation.animation ? ('rg-line-anm-' + relation.animation) : undefined,
          checked ? 'c-rg-line-checked' : undefined
        ].join(' ')}
        stroke={relation.color ? relation.color : options.defaultLineColor}
        style={{
          opacity: relation.opacity,
          'strokeWidth': (relation.lineWidth ? relation.lineWidth : options.defaultLineWidth) + 'px'
        }}
        markerStart={showStartArrow}
        markerEnd={showEndArrow}
        fill="none"
        onTouchStart={(e) => onClick(e)}
        onClick={(e) => onClick(e)}
      />
      {options.defaultShowLineLabel && options.canvasZoom > 40 && (
        <g transform={pathData.textTransform}>
          <text
            key={'t-' + relation.seeks_id}
            x={relation.textOffset_x || options.defaultLineTextOffset_x || 0}
            y={relation.textOffset_y || options.defaultLineTextOffset_y || 10}
            style={{
              opacity: relation.opacity,
              fill: relation.fontColor ? relation.fontColor : (options.defaultLineFontColor ? options.defaultLineFontColor : (relation.color ? relation.color : options.defaultLineColor))
            }}
            className="c-rg-line-text"
            onTouchStart={(e) => onClick(e)}
            onClick={(e) => onClick(e)}
          >
            {relation.text}
          </text>
        </g>
      )}
    </g>
  );
};

export default RGLineSmart;
