// relation-graph-vue3/src/relation-graph/src/core4vue3/RGLinePath.vue
<script lang="ts" setup>
import { computed, inject } from 'vue'
import { relationGraphKey } from '../../../constants'
import type { RGLine, RGLink } from '../RelationGraph'

const props = defineProps<{
  link: RGLink
  relation: RGLine
  relationIndex: number
}>()
const relationGraph = inject(relationGraphKey)!.value
const checked = computed(() => {
  return props.link.seeks_id === relationGraph.options.checkedLineId
})
const pathData = computed(() => {
  const { path, textPosition } = relationGraph.createLinePath(
    props.link,
    props.relation,
    props.relationIndex
  )
  return path
})
</script>
<template>
  <path
    :id="
      relationGraph.options.instanceId +
      '-' +
      link.seeks_id +
      '-' +
      relationIndex
    "
    :d="pathData"
    :stroke="
      checked
        ? relationGraph.options.checkedLineColor
        : relation.color
        ? relation.color
        : relationGraph.options.defaultLineColor
    "
    :style="{
      'opacity': relation.opacity,
      'stroke-width':
        (relation.lineWidth
          ? relation.lineWidth
          : relationGraph.options.defaultLineWidth) + 'px',
    }"
    :marker-start="
      relation.showStartArrow && relationGraph.getArrow(relation, link, true)
    "
    :marker-end="
      relation.showEndArrow && relationGraph.getArrow(relation, link, false)
    "
    :class="[relation.styleClass, checked ? 'c-rg-line-checked' : '']"
    fill="none"
  />
</template>

// relation-graph-react/src/relation-graph/src/core4react/RGLinePath.tsx
import React, { useContext } from 'react';
import { RelationGraphStoreContext } from './store/reducers/StockStore';
import type { RGLineProps } from './RGLineSmart';

const RGLinePath: React.FC<RGLineProps> = ({link,relation,relationIndex}) => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const options = relationGraph.options;
  const checked = link.seeks_id === options.checkedLineId;

  const pathData = () => {
    const { path } = relationGraph.createLinePath(
      link,
      relation,
      relationIndex
    );
    return path;
  };
  const showStartArrow = relation.showStartArrow ? relationGraph.getArrow(relation, link, true) : undefined;
  const showEndArrow = relation.showEndArrow ? relationGraph.getArrow(relation, link, false) : undefined;
  return (
    <path
      id={`${options.instanceId}-${link.seeks_id}-${relationIndex}`}
      d={pathData()}
      stroke={relation.color ? relation.color : options.defaultLineColor}
      style={{
        opacity: relation.opacity,
        strokeWidth: `${
          relation.lineWidth ? relation.lineWidth : options.defaultLineWidth
        }px`,
      }}
      markerStart={showStartArrow}
      markerEnd={showEndArrow}
      className={`c-rg-line-path ${relation.styleClass} ${
        checked ? 'c-rg-line-checked' : ''
      }`}
      fill="none"
    />
  );
};

export default RGLinePath;
