// packages/platforms/react/src/relation-graph/src/core4react/widgets/GraphLoading.tsx
import React, { useContext, useState } from 'react';
import { RelationGraphStoreContext } from '../store/reducers/StockStore';

const GraphLoading: React.FC = () => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const options = relationGraph && relationGraph.options;
  const clickGraphMask = (e) => {
    relationGraph.clickGraphMask(e);
  }
  return (
    <>
    {
      options && <div
    className={`rel-graph-loading ${!options.graphLoading ? 'rel-graph-loading-hide' : ''}`}
    onClick={(e) => {clickGraphMask(e);}}
  >
    <div className="rel-graph-loading-message">
      <svg className="c-graph-loading-icon" aria-hidden="true">
        <use xlinkHref="#icon-lianjiezhong"></use>
      </svg>
      Loading...
    </div>
  </div>
}
    </>
  );
};

export default GraphLoading;

// packages/platforms/vue3/src/relation-graph/src/core4vue3/widgets/GraphLoading.vue
<script lang="ts" setup>
import {computed, inject} from "vue";
import {graphInstanceKey, graphKey} from "../../../../constants";
// const graphInstance$ = inject(graphInstanceKey)
const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})
const clickGraphMask = (e) => {
  graph.instance!.clickGraphMask(e);
}
</script>
<template>
  <div
      class="rel-graph-loading"
      :class="{'rel-graph-loading-hide': !options.graphLoading}"
      @click="clickGraphMask"
  >
    <div class="rel-graph-loading-message">
      <svg class="c-graph-loading-icon" aria-hidden="true"><use xlink:href="#icon-lianjiezhong"></use></svg>
      Loading...
    </div>
  </div>
</template>
