// packages/platforms/react/src/relation-graph/src/core4react/RGLink.tsx
import React, {useContext, useEffect} from 'react';
import RGLineSmart from './RGLineSmart';
import RGLineTextByPath from './RGLineTextByPath';
import RGNodesAnalytic from '../../../../../../relation-graph-models/utils/RGNodesAnalytic';
import {RelationGraphStoreContext} from './store/reducers/StockStore';
import type { RGLink, RGNode, RGLineSlotProps } from '../../../../../../relation-graph-models/types';
export interface RGLinkProps {
  linkProps: RGLink
  LineSlot?: React.FC<RGLineSlotProps>
}
const SeeksRGLink = ({ linkProps, LineSlot }:RGLinkProps) => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const isAllowShowNode = (thisNode:RGNode) => {
    return RGNodesAnalytic.isAllowShowNode(thisNode);
  };

  useEffect(() => {
    // mounted logic here
  }, []);

  const options = relationGraph.options;
  return isAllowShowNode(linkProps.fromNode) && isAllowShowNode(linkProps.toNode) && (
    <g
      className={[
        'rel-link-peel',
        options.checkedLinkId === linkProps.seeks_id ? 'c-rg-link-checked' : ''
      ].join(' ')}
      transform="translate(0,0)"
      data-id={linkProps.seeks_id}
    >
      {linkProps.relations.map((thisRelation, ri) =>
        thisRelation.isHide !== true && <React.Fragment key={thisRelation.id}>
          {
            LineSlot ?
              <LineSlot relationGraph={relationGraph} link={linkProps} line={thisRelation} lineIndex={ri}  />
              :
              (
                (thisRelation.useTextPath !== undefined ? thisRelation.useTextPath : options.lineUseTextPath) ?
                  <RGLineTextByPath link={linkProps} relation={thisRelation} relationIndex={ri} />
                  :
                  <RGLineSmart link={linkProps} relation={thisRelation} relationIndex={ri} />
              )
          }
        </React.Fragment>
      )}
    </g>
  );
};

export default SeeksRGLink;

// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGLink.vue
<script lang="ts" setup>
import {computed, inject} from 'vue'
import {graphInstanceKey, graphKey} from '../../../constants'
import RGLineTextByPath from './RGLineTextByPath.vue'
import RGLineSmart from './RGLineSmart.vue'
import RGNodesAnalytic from '../../../../../../relation-graph-models/utils/RGNodesAnalytic'
import type { RGLink, RGNode } from '../../../../../../relation-graph-models/types';
const props = defineProps<{
  linkProps: RGLink
}>()
// const graphInstance$ = inject(graphInstanceKey)
const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})
const isAllowShowNode = (thisNode:RGNode):boolean => {
  return RGNodesAnalytic.isAllowShowNode(thisNode);
}
</script>
<template>
  <g
      v-if="isAllowShowNode(linkProps.fromNode) && isAllowShowNode(linkProps.toNode)"
      :class="[options.checkedLinkId==linkProps.seeks_id?'c-rg-link-checked':'']"
      ref="seeksRGLink"
      transform="translate(0,0)"
      class="rel-link-peel"
      :data-id="linkProps.seeks_id"
  >
    <template v-for="(thisRelation, ri) in linkProps.relations">
      <slot name="line" :line="thisRelation" :relation-index="ri">
        <RGLineTextByPath v-if="(thisRelation.useTextPath !== undefined ? thisRelation.useTextPath : options.lineUseTextPath) && thisRelation.isHide !== true" :key="'l-'+thisRelation.id" :link="linkProps" :relation="thisRelation" :relation-index="ri" />
        <RGLineSmart v-else-if="thisRelation.isHide !== true" :key="'l-'+thisRelation.id" :link="linkProps" :relation="thisRelation" :relation-index="ri" />
      </slot>
    </template>
  </g>
</template>
