// packages/platforms/react/src/relation-graph/src/core4react/editing/RGEditingController.tsx
import React, { useContext } from 'react';
import {RelationGraphStoreContext, RGUpdateSingalContext} from '../store/reducers/StockStore';

const RGEditingController:React.FC = ({ children }) => {
  const updateSingal = useContext(RGUpdateSingalContext);
  const graphInstance = useContext(RelationGraphStoreContext);
  const options = graphInstance && graphInstance.options;

  if (!options.editingController.show || options.snapshotting) {
    return null;
  }

  const style = {
    left: options.editingController.x + 'px',
    top: options.editingController.y + 'px',
    width: options.editingController.width + 'px',
    height: options.editingController.height + 'px',
  };

  return (
    <div className="rel-editing-ctrl" style={style}>
      {children}
    </div>
  );
};

export default RGEditingController;

// packages/platforms/vue3/src/relation-graph/src/core4vue3/editing/RGEditingController.vue
<template>
  <div
    v-if="options.editingController.show || options.snapshotting"
    class="rel-editing-ctrl"
    :style="{
      left: options.editingController.x + 'px',
      top: options.editingController.y + 'px',
      width: options.editingController.width + 'px',
      height: options.editingController.height + 'px',
    }"
  >
    <slot />
  </div>
</template>

<script lang="ts" setup>
import {computed, inject} from "vue";
import {graphKey} from "../../../../constants";

const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})

</script>

<style scoped>
</style>
