// packages/platforms/react/src/relation-graph/src/core4react/editing/RGEditingNearNodeWidget.tsx
import React from 'react';
import {RGWidgetPosition, RGWidgetProps} from '../../../../types';

const RGEditingNearNodeWidget: React.FC<RGWidgetProps> = ({ position, children }) => {
  const _position: RGWidgetPosition = position || 'top';
  return (
    <div
      className={`rel-editing-bar rel-editing-bar-${_position}`}
    >
      {children}
    </div>
  );
};

export default RGEditingNearNodeWidget;

// packages/platforms/vue3/src/relation-graph/src/core4vue3/editing/RGEditingNearNodeWidget.vue
<template>
  <div
    class="rel-editing-bar"
    :class="['rel-editing-bar-' + (position || 'top')]"
  >
    <slot />
  </div>
</template>

<script lang="ts" setup>
import {computed, inject, onMounted, onUnmounted} from "vue";
import {RGUserEvent, RGWidgetPosition, RGWidgetProps} from "../../../../types";
import {graphKey} from "../../../../constants";

const props = defineProps<{
  position?: RGWidgetPosition
}>(); // RGWidgetProps
const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})
const graphInstance = computed(() => {
  return graph!.instance!;
})
</script>
