// relation-graph-vue3/src/relation-graph/src/core4vue3/widgets/GraphDebugPanel.vue
<script lang="ts" setup>
import { inject, ref, computed } from 'vue'
import { devLog } from '../../../../../../relation-graph-vue2/src/utils/RGCommon'
import {graphInstanceKey, graphKey} from '../../../../constants'
const graphInstance$ = inject(graphInstanceKey)
const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})
const showSettingPanel = ref(false)
const toggleSettingPanel = () => {
  showSettingPanel.value = !showSettingPanel.value
}
const printOptions = () => {
  graphInstance$?.value!.printOptions();
}
const printData = () => {
  graphInstance$?.value!.printData();
}
const enableDevlog = () => {
  graphInstance$?.value!.enableDebugLog(!options.value.debug)
  devLog('debugLog:', graphInstance$?.value!.options.debug)
}
</script>
<template>
  <div>
    <div :class="[]" class="c-setting-panel-button" @click="toggleSettingPanel">
      Debug
    </div>
    <div v-if="showSettingPanel" :class="[]" class="c-setting-panel">
      <div class="c-debug-tools-row"><button @click="printOptions">print options in console</button></div>
      <div class="c-debug-tools-row"><button @click="printData">print json data in console</button></div>
      <div class="c-debug-tools-row">debug log status: {{options.debug}}<button @click="enableDevlog">{{options.debug?'disable':'enable'}} debug log</button></div>
    </div>
  </div>
</template>

// relation-graph-react/src/relation-graph/src/core4react/widgets/GraphDebugPanel.tsx
import React, { useContext, useState } from 'react';
import { devLog } from '../../../../../../relation-graph-vue2/src/utils/RGCommon';
import { RGUpdateContext, RelationGraphStoreContext } from '../store/reducers/StockStore';

const GraphDebugPanel: React.FC = () => {
  const relationGraph = useContext(RelationGraphStoreContext);
  const updateView = useContext(RGUpdateContext);
  const options = relationGraph.options;
  const [showSettingPanel, setShowSettingPanel] = useState(false);
  const toggleSettingPanel = () => {
    setShowSettingPanel(!showSettingPanel);
  };
  const printOptions = () => {
    relationGraph.printOptions();
  };
  const printData = () => {
    relationGraph.getGraphJsonData();
  };
  const enableDevlog = () => {
    relationGraph.enableDebugLog(!options.debug);
    devLog('debugLog:', options.debug);
    updateView();
  };
  return (
    <div>
      <div className="c-setting-panel-button" onClick={()=>{toggleSettingPanel();}}>
        Debug
      </div>
      {
        showSettingPanel &&
        <div className="c-setting-panel">
          <div className="c-debug-tools-row">
            <button onClick={()=>{printOptions();}}>print options in console</button>
          </div>
          <div className="c-debug-tools-row">
            <button onClick={()=>{printData();}}>print json data in console</button>
          </div>
          <div className="c-debug-tools-row">
            debug log status: {options.debug ? 'true' : 'false'}
            <button onClick={()=>{enableDevlog();}}>
              { options.debug ? 'disable' : 'enable' } debug log
            </button>
          </div>
        </div>
      }
    </div>
  );
};

export default GraphDebugPanel;
