// packages/platforms/vue3/src/relation-graph/src/core4vue3/editing/RGEditingConnectController.vue
<template>
  <div
    v-if="options.nodeConnectController.show"
    class="rel-editing-connect-ctrl"
    :style="{
      left: options.nodeConnectController.x + 'px',
      top: options.nodeConnectController.y + 'px',
      width: options.nodeConnectController.width + 'px',
      height: options.nodeConnectController.height + 'px',
    }"
  >
    <slot>
      <RGEditingConnectPoints />
    </slot>
  </div>
</template>

<script lang="ts" setup>
import {computed, inject} from "vue";
import {graphKey} from "../../../../constants";
import RGEditingConnectPoints from "./RGEditingConnectPoints.vue";
const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})
</script>

<style scoped>
</style>

// packages/platforms/react/src/relation-graph/src/core4react/editing/RGEditingConnectController.tsx
import React, { useContext } from 'react';
import RGEditingConnectPoints from './RGEditingConnectPoints';
import {RelationGraphStoreContext, RGUpdateSingalContext} from '../store/reducers/StockStore';

const RGEditingConnectController:React.FC = ({children}) => {
  const updateSingal = useContext(RGUpdateSingalContext);
  const graphInstance = useContext(RelationGraphStoreContext);
  const options = graphInstance && graphInstance.options;

  if (!options.nodeConnectController.show) {
    return null;
  }

  return (
    <div
      className="rel-editing-connect-ctrl"
      style={{
        left: options.nodeConnectController.x + 'px',
        top: options.nodeConnectController.y + 'px',
        width: options.nodeConnectController.width + 'px',
        height: options.nodeConnectController.height + 'px',
      }}
    >
      {
        children ? children : <RGEditingConnectPoints />
      }
    </div>
  );
};

export default RGEditingConnectController;
