// packages/platforms/vue2/src/core4vue/editing/RGEditingResize.vue
<template>
  <div
    class="rel-resize-ctl"
  >
    <div v-if="options.editingController.width > 30" class="rel-resize-ctl-handler rel-resize-ctl-tl" @mousedown="onMouseDown('tl', $event)"></div>
    <div v-if="options.editingController.width > 30" class="rel-resize-ctl-handler rel-resize-ctl-tr" @mousedown="onMouseDown('tr', $event)"></div>
    <div v-if="options.editingController.width > 30" class="rel-resize-ctl-handler rel-resize-ctl-bl" @mousedown="onMouseDown('bl', $event)"></div>
    <div class="rel-resize-ctl-handler rel-resize-ctl-br" @mousedown="onMouseDown('br', $event)"></div>
    <div v-if="options.editingController.width > 60" class="rel-resize-ctl-handler rel-resize-ctl-t" @mousedown="onMouseDown('t', $event)"></div>
    <div v-if="options.editingController.width > 60" class="rel-resize-ctl-handler rel-resize-ctl-b" @mousedown="onMouseDown('b', $event)"></div>
    <div v-if="options.editingController.height > 60" class="rel-resize-ctl-handler rel-resize-ctl-l" @mousedown="onMouseDown('l', $event)"></div>
    <div v-if="options.editingController.height > 60" class="rel-resize-ctl-handler rel-resize-ctl-r" @mousedown="onMouseDown('r', $event)"></div>
  </div>
</template>

<script lang="ts">
export default {
  name: 'RGEditingResize',
  components: {},
  inject: ['graph', 'graphInstance'],
  computed: {
    options() {
      return this.graph.options;
    },
    relationGraph() {
      return this.graphInstance();
    }
  },
  data() {
    return {
    };
  },
  methods: {
    onMouseDown(type, $event) {
      $event.stopPropagation();
      // console.log('Resize start:', type);
      this.relationGraph.onResizeStart(type, $event);
    }
  }
};
</script>

<style scoped>
</style>

// packages/platforms/react/src/relation-graph/src/core4react/editing/RGEditingResize.tsx
import React, { useContext } from 'react';
import {RelationGraphStoreContext, RGUpdateSingalContext} from '../store/reducers/StockStore';
import {RGResizeHandlePosition} from "../../../../types";

const RGEditingResize:React.FC = () => {
  const graphInstance = useContext(RelationGraphStoreContext);
  const updateSingal = useContext(RGUpdateSingalContext);
  const options = graphInstance && graphInstance.options;

  const onMouseDown = (type: RGResizeHandlePosition, event: React.MouseEvent) => {
    event.stopPropagation();
    // console.log('Resize start:', type);
    graphInstance.onResizeStart(type, event.nativeEvent);
  };

  return (
    <div className="rel-resize-ctl">
      {options.editingController.width > 30 && (
        <div
          className="rel-resize-ctl-handler rel-resize-ctl-tl"
          onMouseDown={(event) => onMouseDown('tl', event)}
        ></div>
      )}
      {options.editingController.width > 30 && (
        <div
          className="rel-resize-ctl-handler rel-resize-ctl-tr"
          onMouseDown={(event) => onMouseDown('tr', event)}
        ></div>
      )}
      {options.editingController.width > 30 && (
        <div
          className="rel-resize-ctl-handler rel-resize-ctl-bl"
          onMouseDown={(event) => onMouseDown('bl', event)}
        ></div>
      )}
      <div
        className="rel-resize-ctl-handler rel-resize-ctl-br"
        onMouseDown={(event) => onMouseDown('br', event)}
      ></div>
      {options.editingController.width > 60 && (
        <div
          className="rel-resize-ctl-handler rel-resize-ctl-t"
          onMouseDown={(event) => onMouseDown('t', event)}
        ></div>
      )}
      {options.editingController.width > 60 && (
        <div
          className="rel-resize-ctl-handler rel-resize-ctl-b"
          onMouseDown={(event) => onMouseDown('b', event)}
        ></div>
      )}
      {options.editingController.height > 60 && (
        <div
          className="rel-resize-ctl-handler rel-resize-ctl-l"
          onMouseDown={(event) => onMouseDown('l', event)}
        ></div>
      )}
      {options.editingController.height > 60 && (
        <div
          className="rel-resize-ctl-handler rel-resize-ctl-r"
          onMouseDown={(event) => onMouseDown('r', event)}
        ></div>
      )}
    </div>
  );
};

export default RGEditingResize;
