// packages/platforms/vue2/src/core4vue/editing/RGEditingConnectController.vue
<template>
  <div
    v-if="options.nodeConnectController.show"
    class="rel-editing-connect-ctrl"
    :style="{
      left: options.nodeConnectController.x + 'px',
      top: options.nodeConnectController.y + 'px',
      width: options.nodeConnectController.width + 'px',
      height: options.nodeConnectController.height + 'px',
    }"
  >
    <slot>
      <RGEditingConnectPoints />
    </slot>
  </div>
</template>

<script lang="ts">
import RGEditingConnectPoints from "./RGEditingConnectPoints.vue";

export default {
  name: 'RGEditingConnectController',
  components: {RGEditingConnectPoints},
  inject: ['graph', 'graphInstance'],
  computed: {
    options() {
      return this.graph.options;
    },
    relationGraph() {
      return this.graphInstance();
    }
  },
  data() {
    return {
    };
  },
  methods: {
  }
};
</script>

<style scoped>
</style>

// packages/platforms/react/src/relation-graph/src/core4react/editing/RGEditingConnectController.tsx
import React, { useContext } from 'react';
import RGEditingConnectPoints from './RGEditingConnectPoints';
import {RelationGraphStoreContext, RGUpdateSingalContext} from '../store/reducers/StockStore';

const RGEditingConnectController:React.FC = ({children}) => {
  const updateSingal = useContext(RGUpdateSingalContext);
  const graphInstance = useContext(RelationGraphStoreContext);
  const options = graphInstance && graphInstance.options;

  if (!options.nodeConnectController.show) {
    return null;
  }

  return (
    <div
      className="rel-editing-connect-ctrl"
      style={{
        left: options.nodeConnectController.x + 'px',
        top: options.nodeConnectController.y + 'px',
        width: options.nodeConnectController.width + 'px',
        height: options.nodeConnectController.height + 'px',
      }}
    >
      {
        children ? children : <RGEditingConnectPoints />
      }
    </div>
  );
};

export default RGEditingConnectController;
