// packages/platforms/vue2/src/core4vue/editing/RGEditingController.vue
<template>
  <div
    v-if="options.editingController.show || options.snapshotting"
    class="rel-editing-ctrl"
    :style="{
      left: options.editingController.x + 'px',
      top: options.editingController.y + 'px',
      width: options.editingController.width + 'px',
      height: options.editingController.height + 'px',
    }"
  >
    <slot />
  </div>
</template>

<script lang="ts">
import RGEditingToolbar from "./RGEditingNearNodeWidget.vue";
import RGEditingResize from "./RGEditingResize.vue";
import RGEditingCreateLineHandle from "./RGEditingCreateLineHandle.vue";

export default {
  name: 'RGEditingController',
  components: {RGEditingCreateLineHandle, RGEditingResize, RGEditingToolbar},
  inject: ['graph', 'graphInstance'],
  computed: {
    options() {
      return this.graph.options;
    },
    relationGraph() {
      return this.graphInstance();
    }
  },
  data() {
    return {
    };
  },
  methods: {
  }
};
</script>

<style scoped>
</style>

// packages/platforms/react/src/relation-graph/src/core4react/editing/RGEditingController.tsx
import React, { useContext } from 'react';
import {RelationGraphStoreContext, RGUpdateSingalContext} from '../store/reducers/StockStore';

const RGEditingController:React.FC = ({ children }) => {
  const updateSingal = useContext(RGUpdateSingalContext);
  const graphInstance = useContext(RelationGraphStoreContext);
  const options = graphInstance && graphInstance.options;

  if (!options.editingController.show || options.snapshotting) {
    return null;
  }

  const style = {
    left: options.editingController.x + 'px',
    top: options.editingController.y + 'px',
    width: options.editingController.width + 'px',
    height: options.editingController.height + 'px',
  };

  return (
    <div className="rel-editing-ctrl" style={style}>
      {children}
    </div>
  );
};

export default RGEditingController;
