// packages/platforms/vue3/src/relation-graph/src/core4vue3/editing/RGEditingCreateLineHandle.vue
<template>
  <div
    v-if="options.editingController.nodes.length === 1"
    class="rel-editing-line-handle"
    @mousedown="onMouseDown('br', $event)"
  >
    <slot />
  </div>
</template>

<script lang="ts" setup>

import {RGWidgetPosition, RGUserEvent, RGCreateLineHandleProps, JsonLine} from "../../../../types";
import {computed, inject} from "vue";
import {graphKey} from "../../../../constants";

const props = defineProps<{
  lineTemplate?: JsonLine
}>(); // RGCreateLineHandleProps
const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})
const graphInstance = computed(() => {
  return graph!.instance!;
})
const onMouseDown = (type: RGWidgetPosition, $event: RGUserEvent) => {
  graphInstance.value.startCreateLineByTemplate(type, props.lineTemplate, $event);
}
</script>

<style scoped>
</style>

// packages/platforms/react/src/relation-graph/src/core4react/editing/RGEditingCreateLineHandle.tsx
import React, { useContext } from 'react';
import {RGWidgetPosition, RGCreateLineHandleProps} from '../../../../types';
import {RelationGraphStoreContext, RGUpdateSingalContext} from '../store/reducers/StockStore';

const RGEditingCreateLineHandle:React.FC<RGCreateLineHandleProps> = ({ lineTemplate, children }) => {
  const updateSingal = useContext(RGUpdateSingalContext);
  const graphInstance = useContext(RelationGraphStoreContext);
  const options = graphInstance && graphInstance.options;

  const onMouseDown = (type: RGWidgetPosition, event: React.MouseEvent) => {
    graphInstance.startCreateLineByTemplate(type, lineTemplate, event.nativeEvent);
  };

  if (options.editingController.nodes.length !== 1) {
    return null;
  }

  return (
    <div
      className="rel-editing-line-handle"
      onMouseDown={(event) => onMouseDown('br', event)}
    >
      {children}
    </div>
  );
};

export default RGEditingCreateLineHandle;
