// packages/platforms/vue2/src/core4vue/editing/RGEditingConnectPoints.vue
<template>
  <div
    class="rel-connect-ctl"
  >
    <div class="rel-connect-ctl-handler rel-connect-ctl-t" data-point="top" @mouseup="onMouseUp('top', $event)"></div>
    <div class="rel-connect-ctl-handler rel-connect-ctl-b" data-point="bottom" @mouseup="onMouseUp('bottom', $event)"></div>
    <div class="rel-connect-ctl-handler rel-connect-ctl-center" data-point="border" @mouseup="onMouseUp('border', $event)"></div>
    <div class="rel-connect-ctl-handler rel-connect-ctl-l" data-point="left" @mouseup="onMouseUp('left', $event)"></div>
    <div class="rel-connect-ctl-handler rel-connect-ctl-r" data-point="right" @mouseup="onMouseUp('right', $event)"></div>
    <div class="rel-connect-ctl-handler rel-connect-ctl-lr" data-point="lr" @mouseup="onMouseUp('lr', $event)"></div>
    <div class="rel-connect-ctl-handler rel-connect-ctl-tb" data-point="tb" @mouseup="onMouseUp('tb', $event)"></div>
  </div>
</template>

<script lang="ts">
export default {
  name: 'RGEditingConnectPoints',
  components: {},
  inject: ['graph', 'graphInstance'],
  computed: {
    options() {
      return this.graph.options;
    },
    relationGraph() {
      return this.graphInstance();
    }
  },
  data() {
    return {
    };
  },
  methods: {
    onMouseUp(type, $event) {
      this.relationGraph.onLineVertexBeDropped(type, $event);
    }
  }
};
</script>

<style scoped>
</style>

// packages/platforms/react/src/relation-graph/src/core4react/editing/RGEditingConnectPoints.tsx
import React, { useContext } from 'react';
import {RelationGraphStoreContext} from '../store/reducers/StockStore';
import {RGJunctionPoint} from "../../../../types";

const RGEditingConnectPoints = () => {
  const graphInstance = useContext(RelationGraphStoreContext);

  const onMouseUp = (type: RGJunctionPoint, event: React.MouseEvent) => {
    graphInstance.onLineVertexBeDropped(type, event.nativeEvent);
  };

  return (
    <div className="rel-connect-ctl">
      <div
        className="rel-connect-ctl-handler rel-connect-ctl-t"
        data-point="top"
        onMouseUp={(event) => onMouseUp('top', event)}
      />
      <div
        className="rel-connect-ctl-handler rel-connect-ctl-b"
        data-point="bottom"
        onMouseUp={(event) => onMouseUp('bottom', event)}
      />
      <div
        className="rel-connect-ctl-handler rel-connect-ctl-center"
        data-point="border"
        onMouseUp={(event) => onMouseUp('border', event)}
      />
      <div
        className="rel-connect-ctl-handler rel-connect-ctl-l"
        data-point="left"
        onMouseUp={(event) => onMouseUp('left', event)}
      />
      <div
        className="rel-connect-ctl-handler rel-connect-ctl-r"
        data-point="right"
        onMouseUp={(event) => onMouseUp('right', event)}
      />
      <div
        className="rel-connect-ctl-handler rel-connect-ctl-lr"
        data-point="lr"
        onMouseUp={(event) => onMouseUp('lr', event)}
      />
      <div
        className="rel-connect-ctl-handler rel-connect-ctl-tb"
        data-point="tb"
        onMouseUp={(event) => onMouseUp('tb', event)}
      />
    </div>
  );
};

export default RGEditingConnectPoints;
