// packages/platforms/vue3/src/relation-graph/src/core4vue3/editing/RGMiniView.vue
<template>
  <div
    class="rel-miniview"
    :class="['rel-miniview-' + (position || 'br')]"
    ref="$rgMiniView"
  >
    <canvas
      ref="$rgMiniViewCanvas"
      :class="{
      'rel-mv-canvas-reset': options.miniViewVisibleHandle.emptyContent
      }"
      @click="onClickCanvas"
    />
    <div
      class="rel-mv-visible-area"
      @mousedown="onMouseDown"
      :style="{
      left: options.miniViewVisibleHandle.x + 'px',
      top: options.miniViewVisibleHandle.y + 'px',
      width: options.miniViewVisibleHandle.width + 'px',
      height: options.miniViewVisibleHandle.height + 'px'
    }"
    ></div>
  </div>
</template>

<script lang="ts" setup>
import {RGMiniViewProps, RGUserEvent, RGWidgetPosition} from "../../../../types";
import {onMounted, onUnmounted, ref, computed, inject} from "vue";
import {graphKey} from "../../../../constants";
const graph = inject(graphKey)
const options = computed(() => {
  return graph!.options!;
})
const graphInstance = computed(() => {
  return graph!.instance!;
})
const props = defineProps<{
  position?: RGWidgetPosition,
  width?: string,
  height?: string
}>(); // RGMiniViewProps
const $rgMiniView = ref<HTMLDivElement>();
const $rgMiniViewCanvas = ref<HTMLCanvasElement>();
onMounted(() => {
  options.value.showMiniView = true;
  $rgMiniView.value!.style.setProperty('--mv-width', (props.width || '150px'));
  $rgMiniView.value!.style.setProperty('--mv-height', (props.height || '150px'));
  graphInstance.value.setMiniViewCanvas($rgMiniViewCanvas.value!);
});
onUnmounted(() => {
  options.value.showMiniView = false;
});
const onMouseDown = (e: RGUserEvent) => {
  graphInstance.value.onVisiableViewHandleDragStart(e);
}
const onClickCanvas = (e: RGUserEvent) => {
  graphInstance.value.resetByVisiableView(e);
}
</script>

// packages/platforms/react/src/relation-graph/src/core4react/editing/RGMiniView.tsx
import React, { useEffect, useRef } from 'react';
import { useContext } from 'react';
import {RelationGraphStoreContext, RGUpdateSingalContext} from '../store/reducers/StockStore';
import {RGMiniViewProps} from "../../../../../../../relation-graph-models/types";

const RGMiniView:React.FC<RGMiniViewProps> = ({ position = 'br', width, height }) => {
  const graphInstance = useContext(RelationGraphStoreContext);
  const updateSingal = useContext(RGUpdateSingalContext);
  const options = graphInstance && graphInstance.options;
  const $rgMiniView = useRef<HTMLDivElement>(null);
  const $rgMiniViewCanvas = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    options.showMiniView = true;
    $rgMiniView.current!.style.setProperty('--mv-width', width || '150px');
    $rgMiniView.current!.style.setProperty('--mv-height', height || '150px');
    graphInstance.setMiniViewCanvas($rgMiniViewCanvas.current!);

    return () => {
      options.showMiniView = false;
    };
  }, []);

  const onMouseDown = (e: React.MouseEvent) => {
    graphInstance.onVisiableViewHandleDragStart(e.nativeEvent);
  };

  const onClickCanvas = async(e: React.MouseEvent) => {
    graphInstance.resetByVisiableView(e.nativeEvent);
  };

  return (
    <div
      className={`rel-miniview rel-miniview-${position}`}
      ref={$rgMiniView}
    >
      <canvas
        ref={$rgMiniViewCanvas}
        className={
          options.miniViewVisibleHandle.emptyContent
            ? 'rel-mv-canvas-reset'
            : ''
        }
        onClick={onClickCanvas}
      />
      <div
        className="rel-mv-visible-area"
        onMouseDown={onMouseDown}
        style={{
          left: options.miniViewVisibleHandle.x + 'px',
          top: options.miniViewVisibleHandle.y + 'px',
          width: options.miniViewVisibleHandle.width + 'px',
          height: options.miniViewVisibleHandle.height + 'px',
        }}
      ></div>
    </div>
  );
};

export default RGMiniView;
